//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaigrSearchDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KaigrSearchDB : DbContext
    {
        public KaigrSearchDB()
            : base("name=KaigrSearchDB")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 480;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RPT_ProcessingIterationMaster> RPT_ProcessingIterationMaster { get; set; }
    
        [DbFunction("KaigrSearchDB", "FN_MONTHYEAR")]
        public virtual IQueryable<FN_MONTHYEAR_Result> FN_MONTHYEAR(Nullable<int> yEAR)
        {
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_MONTHYEAR_Result>("[KaigrSearchDB].[FN_MONTHYEAR](@YEAR)", yEARParameter);
        }
    
        public virtual ObjectResult<USP_RPT_DAILY_REVENUE_DAYWISE_Result> USP_RPT_DAILY_REVENUE_DAYWISE(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE, Nullable<int> rEGARTICLECODE, Nullable<int> mONTH, Nullable<int> yEAR)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            var rEGARTICLECODEParameter = rEGARTICLECODE.HasValue ?
                new ObjectParameter("REGARTICLECODE", rEGARTICLECODE) :
                new ObjectParameter("REGARTICLECODE", typeof(int));
    
            var mONTHParameter = mONTH.HasValue ?
                new ObjectParameter("MONTH", mONTH) :
                new ObjectParameter("MONTH", typeof(int));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RPT_DAILY_REVENUE_DAYWISE_Result>("USP_RPT_DAILY_REVENUE_DAYWISE", dISTRICTCODEParameter, sROCODEParameter, rEGARTICLECODEParameter, mONTHParameter, yEARParameter);
        }
    
        public virtual ObjectResult<USP_RPT_DAILY_REVENUE_DOCUMENTWISE_Result> USP_RPT_DAILY_REVENUE_DOCUMENTWISE(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE, Nullable<int> rEGARTICLECODE, Nullable<int> yEAR)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            var rEGARTICLECODEParameter = rEGARTICLECODE.HasValue ?
                new ObjectParameter("REGARTICLECODE", rEGARTICLECODE) :
                new ObjectParameter("REGARTICLECODE", typeof(int));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RPT_DAILY_REVENUE_DOCUMENTWISE_Result>("USP_RPT_DAILY_REVENUE_DOCUMENTWISE", dISTRICTCODEParameter, sROCODEParameter, rEGARTICLECODEParameter, yEARParameter);
        }
    
        public virtual ObjectResult<USP_RPT_HIGHVALUE_PROPERTIES_Result> USP_RPT_HIGHVALUE_PROPERTIES(Nullable<int> year, Nullable<int> fromRange, Nullable<int> toRange)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var fromRangeParameter = fromRange.HasValue ?
                new ObjectParameter("fromRange", fromRange) :
                new ObjectParameter("fromRange", typeof(int));
    
            var toRangeParameter = toRange.HasValue ?
                new ObjectParameter("ToRange", toRange) :
                new ObjectParameter("ToRange", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RPT_HIGHVALUE_PROPERTIES_Result>("USP_RPT_HIGHVALUE_PROPERTIES", yearParameter, fromRangeParameter, toRangeParameter);
        }
    
        public virtual ObjectResult<USP_RPT_JurisdictionalWiseDetail_Result> USP_RPT_JurisdictionalWiseDetail(Nullable<int> sROCode, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var sROCodeParameter = sROCode.HasValue ?
                new ObjectParameter("SROCode", sROCode) :
                new ObjectParameter("SROCode", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RPT_JurisdictionalWiseDetail_Result>("USP_RPT_JurisdictionalWiseDetail", sROCodeParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<USP_RPT_SALEDEED_REGISTERED_Result> USP_RPT_SALEDEED_REGISTERED(Nullable<int> dISTRICTCODE, Nullable<int> sROCode, Nullable<int> yEAR, Nullable<int> propertyTypeID, Nullable<int> amountRange)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCodeParameter = sROCode.HasValue ?
                new ObjectParameter("SROCode", sROCode) :
                new ObjectParameter("SROCode", typeof(int));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            var propertyTypeIDParameter = propertyTypeID.HasValue ?
                new ObjectParameter("PropertyTypeID", propertyTypeID) :
                new ObjectParameter("PropertyTypeID", typeof(int));
    
            var amountRangeParameter = amountRange.HasValue ?
                new ObjectParameter("AmountRange", amountRange) :
                new ObjectParameter("AmountRange", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RPT_SALEDEED_REGISTERED_Result>("USP_RPT_SALEDEED_REGISTERED", dISTRICTCODEParameter, sROCodeParameter, yEARParameter, propertyTypeIDParameter, amountRangeParameter);
        }
    
        public virtual ObjectResult<USP_RPT_DAILY_REVENUE_RANGEWISE_Result> USP_RPT_DAILY_REVENUE_RANGEWISE(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE, Nullable<int> rEGARTICLECODE, Nullable<System.DateTime> fROMDATE, Nullable<System.DateTime> tODATE)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            var rEGARTICLECODEParameter = rEGARTICLECODE.HasValue ?
                new ObjectParameter("REGARTICLECODE", rEGARTICLECODE) :
                new ObjectParameter("REGARTICLECODE", typeof(int));
    
            var fROMDATEParameter = fROMDATE.HasValue ?
                new ObjectParameter("FROMDATE", fROMDATE) :
                new ObjectParameter("FROMDATE", typeof(System.DateTime));
    
            var tODATEParameter = tODATE.HasValue ?
                new ObjectParameter("TODATE", tODATE) :
                new ObjectParameter("TODATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RPT_DAILY_REVENUE_RANGEWISE_Result>("USP_RPT_DAILY_REVENUE_RANGEWISE", dISTRICTCODEParameter, sROCODEParameter, rEGARTICLECODEParameter, fROMDATEParameter, tODATEParameter);
        }
    
        public virtual ObjectResult<USP_RPT_DAILY_REVENUE_MONTHWISE_Result> USP_RPT_DAILY_REVENUE_MONTHWISE(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE, Nullable<int> rEGARTICLECODE, Nullable<int> yEAR)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            var rEGARTICLECODEParameter = rEGARTICLECODE.HasValue ?
                new ObjectParameter("REGARTICLECODE", rEGARTICLECODE) :
                new ObjectParameter("REGARTICLECODE", typeof(int));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RPT_DAILY_REVENUE_MONTHWISE_Result>("USP_RPT_DAILY_REVENUE_MONTHWISE", dISTRICTCODEParameter, sROCODEParameter, rEGARTICLECODEParameter, yEARParameter);
        }
    
        public virtual ObjectResult<UPS_DB_GET_TARGET_ACHIEVED_FYWISE_Result> UPS_DB_GET_TARGET_ACHIEVED_FYWISE(Nullable<int> dISTRICTCODE, string fLAG)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UPS_DB_GET_TARGET_ACHIEVED_FYWISE_Result>("UPS_DB_GET_TARGET_ACHIEVED_FYWISE", dISTRICTCODEParameter, fLAGParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_ARTICLELIST_TOP10WISE_Result> USP_DB_GET_ARTICLELIST_TOP10WISE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_ARTICLELIST_TOP10WISE_Result>("USP_DB_GET_ARTICLELIST_TOP10WISE");
        }
    
        public virtual ObjectResult<USP_DB_GET_CURRENT_REVENUE_Result> USP_DB_GET_CURRENT_REVENUE(Nullable<int> dISTRICTCODE, string fLAG, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_CURRENT_REVENUE_Result>("USP_DB_GET_CURRENT_REVENUE", dISTRICTCODEParameter, fLAGParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_CURRENT_REVENUE_DETAILS_Result> USP_DB_GET_CURRENT_REVENUE_DETAILS(Nullable<int> dISTRICTCODE, string fLAG, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_CURRENT_REVENUE_DETAILS_Result>("USP_DB_GET_CURRENT_REVENUE_DETAILS", dISTRICTCODEParameter, fLAGParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_CURRENT_STATUS_Result> USP_DB_GET_CURRENT_STATUS(string fLAG, Nullable<int> districtCode, Nullable<int> fYear)
        {
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            var districtCodeParameter = districtCode.HasValue ?
                new ObjectParameter("DistrictCode", districtCode) :
                new ObjectParameter("DistrictCode", typeof(int));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_CURRENT_STATUS_Result>("USP_DB_GET_CURRENT_STATUS", fLAGParameter, districtCodeParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_FYWISE_PROGRESS_Result> USP_DB_GET_FYWISE_PROGRESS(Nullable<int> dISTRICTCODE)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_FYWISE_PROGRESS_Result>("USP_DB_GET_FYWISE_PROGRESS", dISTRICTCODEParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_HIGH_VALUE_REVENUE_COLLECTED_Result> USP_DB_GET_HIGH_VALUE_REVENUE_COLLECTED(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_HIGH_VALUE_REVENUE_COLLECTED_Result>("USP_DB_GET_HIGH_VALUE_REVENUE_COLLECTED", dISTRICTCODEParameter, sROCODEParameter);
        }
    
        public virtual ObjectResult<USP_DB_Get_HIGHLIGHTS_Result> USP_DB_Get_HIGHLIGHTS(Nullable<int> dISTRICTCODE, string fLAG, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_Get_HIGHLIGHTS_Result>("USP_DB_Get_HIGHLIGHTS", dISTRICTCODEParameter, fLAGParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_OFFICESTARTTIME_Result> USP_DB_GET_OFFICESTARTTIME(Nullable<int> dISTRICTCODE, string fLAG, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_OFFICESTARTTIME_Result>("USP_DB_GET_OFFICESTARTTIME", dISTRICTCODEParameter, fLAGParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_OFFICESTARTTIME_DETAILS_Result> USP_DB_GET_OFFICESTARTTIME_DETAILS(Nullable<int> dISTRICTCODE, string fLAG, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_OFFICESTARTTIME_DETAILS_Result>("USP_DB_GET_OFFICESTARTTIME_DETAILS", dISTRICTCODEParameter, fLAGParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_SALES_STASTICS_Result> USP_DB_GET_SALES_STASTICS(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_SALES_STASTICS_Result>("USP_DB_GET_SALES_STASTICS", dISTRICTCODEParameter, sROCODEParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_SALES_STASTICS_REVENUE_COLLECTED_Result> USP_DB_GET_SALES_STASTICS_REVENUE_COLLECTED(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_SALES_STASTICS_REVENUE_COLLECTED_Result>("USP_DB_GET_SALES_STASTICS_REVENUE_COLLECTED", dISTRICTCODEParameter, sROCODEParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_SUMMARY_TABLE_Result> USP_DB_GET_SUMMARY_TABLE(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE, string regArticleCodeStr)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            var regArticleCodeStrParameter = regArticleCodeStr != null ?
                new ObjectParameter("RegArticleCodeStr", regArticleCodeStr) :
                new ObjectParameter("RegArticleCodeStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_SUMMARY_TABLE_Result>("USP_DB_GET_SUMMARY_TABLE", dISTRICTCODEParameter, sROCODEParameter, regArticleCodeStrParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_SURCHARGE_CESS_Result> USP_DB_GET_SURCHARGE_CESS(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE, string rEGARTICLECODESTR)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            var rEGARTICLECODESTRParameter = rEGARTICLECODESTR != null ?
                new ObjectParameter("REGARTICLECODESTR", rEGARTICLECODESTR) :
                new ObjectParameter("REGARTICLECODESTR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_SURCHARGE_CESS_Result>("USP_DB_GET_SURCHARGE_CESS", dISTRICTCODEParameter, sROCODEParameter, rEGARTICLECODESTRParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_TARGET_ACHIEVED_FYWISE_Result> USP_DB_GET_TARGET_ACHIEVED_FYWISE(Nullable<int> dISTRICTCODE, string fLAG, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_TARGET_ACHIEVED_FYWISE_Result>("USP_DB_GET_TARGET_ACHIEVED_FYWISE", dISTRICTCODEParameter, fLAGParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_TARGET_LINE_Result> USP_DB_GET_TARGET_LINE(Nullable<int> districtCode, Nullable<int> fYear)
        {
            var districtCodeParameter = districtCode.HasValue ?
                new ObjectParameter("districtCode", districtCode) :
                new ObjectParameter("districtCode", typeof(int));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_TARGET_LINE_Result>("USP_DB_GET_TARGET_LINE", districtCodeParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_HIGHVALUE_SUMMARY_Result> USP_DB_HIGHVALUE_SUMMARY(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_HIGHVALUE_SUMMARY_Result>("USP_DB_HIGHVALUE_SUMMARY", dISTRICTCODEParameter, sROCODEParameter, fYearParameter);
        }
    
        public virtual int USP_DB_INSERT_HIGHLIGHTS(Nullable<int> dISTRICTCODE, string fLAG, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_DB_INSERT_HIGHLIGHTS", dISTRICTCODEParameter, fLAGParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_SUMMARY_TABLE_DAYWISE_Result> USP_DB_GET_SUMMARY_TABLE_DAYWISE(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE, string regArticleCodeStr)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            var regArticleCodeStrParameter = regArticleCodeStr != null ?
                new ObjectParameter("RegArticleCodeStr", regArticleCodeStr) :
                new ObjectParameter("RegArticleCodeStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_SUMMARY_TABLE_DAYWISE_Result>("USP_DB_GET_SUMMARY_TABLE_DAYWISE", dISTRICTCODEParameter, sROCODEParameter, regArticleCodeStrParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_SUMMARY_TABLE_FYEARWISE_Result> USP_DB_GET_SUMMARY_TABLE_FYEARWISE(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE, string regArticleCodeStr, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            var regArticleCodeStrParameter = regArticleCodeStr != null ?
                new ObjectParameter("RegArticleCodeStr", regArticleCodeStr) :
                new ObjectParameter("RegArticleCodeStr", typeof(string));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_SUMMARY_TABLE_FYEARWISE_Result>("USP_DB_GET_SUMMARY_TABLE_FYEARWISE", dISTRICTCODEParameter, sROCODEParameter, regArticleCodeStrParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_SUMMARY_TABLE_MONTHWISE_Result> USP_DB_GET_SUMMARY_TABLE_MONTHWISE(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE, string regArticleCodeStr)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            var regArticleCodeStrParameter = regArticleCodeStr != null ?
                new ObjectParameter("RegArticleCodeStr", regArticleCodeStr) :
                new ObjectParameter("RegArticleCodeStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_SUMMARY_TABLE_MONTHWISE_Result>("USP_DB_GET_SUMMARY_TABLE_MONTHWISE", dISTRICTCODEParameter, sROCODEParameter, regArticleCodeStrParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_SUMMARY_TABLE_UPTODATE_Result> USP_DB_GET_SUMMARY_TABLE_UPTODATE(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE, string regArticleCodeStr)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            var regArticleCodeStrParameter = regArticleCodeStr != null ?
                new ObjectParameter("RegArticleCodeStr", regArticleCodeStr) :
                new ObjectParameter("RegArticleCodeStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_SUMMARY_TABLE_UPTODATE_Result>("USP_DB_GET_SUMMARY_TABLE_UPTODATE", dISTRICTCODEParameter, sROCODEParameter, regArticleCodeStrParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_HIGH_VALUE_DOCS_REGISTERED_Result> USP_DB_GET_HIGH_VALUE_DOCS_REGISTERED(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_HIGH_VALUE_DOCS_REGISTERED_Result>("USP_DB_GET_HIGH_VALUE_DOCS_REGISTERED", dISTRICTCODEParameter, sROCODEParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_SALES_STASTICS_DOCS_REGISTERED_Result> USP_DB_GET_SALES_STASTICS_DOCS_REGISTERED(Nullable<int> dISTRICTCODE, Nullable<int> sROCODE)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCODEParameter = sROCODE.HasValue ?
                new ObjectParameter("SROCODE", sROCODE) :
                new ObjectParameter("SROCODE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_SALES_STASTICS_DOCS_REGISTERED_Result>("USP_DB_GET_SALES_STASTICS_DOCS_REGISTERED", dISTRICTCODEParameter, sROCODEParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_TOP3BOTTOM3_AVG_REGISTRASTION_TIME_FYWISE_Result> USP_DB_GET_TOP3BOTTOM3_AVG_REGISTRASTION_TIME_FYWISE(Nullable<int> dISTRICTCODE, string fLAG, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_TOP3BOTTOM3_AVG_REGISTRASTION_TIME_FYWISE_Result>("USP_DB_GET_TOP3BOTTOM3_AVG_REGISTRASTION_TIME_FYWISE", dISTRICTCODEParameter, fLAGParameter, fYearParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_DB_GET_AVG_REGISTRASTION_TIME_FYWISE(Nullable<int> dISTRICTCODE, string fLAG, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_DB_GET_AVG_REGISTRASTION_TIME_FYWISE", dISTRICTCODEParameter, fLAGParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_AVG_REGISTRASTION_TIME_FYWISE_DETAILS_Result> USP_DB_GET_AVG_REGISTRASTION_TIME_FYWISE_DETAILS(Nullable<int> dISTRICTCODE, string fLAG, Nullable<int> fYear)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fLAGParameter = fLAG != null ?
                new ObjectParameter("FLAG", fLAG) :
                new ObjectParameter("FLAG", typeof(string));
    
            var fYearParameter = fYear.HasValue ?
                new ObjectParameter("FYear", fYear) :
                new ObjectParameter("FYear", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_AVG_REGISTRASTION_TIME_FYWISE_DETAILS_Result>("USP_DB_GET_AVG_REGISTRASTION_TIME_FYWISE_DETAILS", dISTRICTCODEParameter, fLAGParameter, fYearParameter);
        }
    
        public virtual ObjectResult<USP_DB_GET_MONTHWISE_PROGRESS_Result> USP_DB_GET_MONTHWISE_PROGRESS(Nullable<int> dISTRICTCODE, Nullable<int> fYEAR)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var fYEARParameter = fYEAR.HasValue ?
                new ObjectParameter("FYEAR", fYEAR) :
                new ObjectParameter("FYEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DB_GET_MONTHWISE_PROGRESS_Result>("USP_DB_GET_MONTHWISE_PROGRESS", dISTRICTCODEParameter, fYEARParameter);
        }
    
        public virtual ObjectResult<USP_RPT_TODAYS_TOTAL_DOCUMENTS_REGISTERED_SUMMARY_TODAYPRESENTED_Result> USP_RPT_TODAYS_TOTAL_DOCUMENTS_REGISTERED_SUMMARY_TODAYPRESENTED(Nullable<int> dISTRICTCODE, Nullable<int> sROCode, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> isDRO, Nullable<int> documentTypeID)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCodeParameter = sROCode.HasValue ?
                new ObjectParameter("SROCode", sROCode) :
                new ObjectParameter("SROCode", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var isDROParameter = isDRO.HasValue ?
                new ObjectParameter("isDRO", isDRO) :
                new ObjectParameter("isDRO", typeof(int));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RPT_TODAYS_TOTAL_DOCUMENTS_REGISTERED_SUMMARY_TODAYPRESENTED_Result>("USP_RPT_TODAYS_TOTAL_DOCUMENTS_REGISTERED_SUMMARY_TODAYPRESENTED", dISTRICTCODEParameter, sROCodeParameter, fromDateParameter, toDateParameter, isDROParameter, documentTypeIDParameter);
        }
    
        public virtual ObjectResult<USP_RPT_TODAYS_TOTAL_DOCUMENTS_REGISTERED_SUMMARY_Result> USP_RPT_TODAYS_TOTAL_DOCUMENTS_REGISTERED_SUMMARY(Nullable<int> dISTRICTCODE, Nullable<int> sROCode, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<int> isDRO, Nullable<int> documentTypeID)
        {
            var dISTRICTCODEParameter = dISTRICTCODE.HasValue ?
                new ObjectParameter("DISTRICTCODE", dISTRICTCODE) :
                new ObjectParameter("DISTRICTCODE", typeof(int));
    
            var sROCodeParameter = sROCode.HasValue ?
                new ObjectParameter("SROCode", sROCode) :
                new ObjectParameter("SROCode", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var isDROParameter = isDRO.HasValue ?
                new ObjectParameter("isDRO", isDRO) :
                new ObjectParameter("isDRO", typeof(int));
    
            var documentTypeIDParameter = documentTypeID.HasValue ?
                new ObjectParameter("DocumentTypeID", documentTypeID) :
                new ObjectParameter("DocumentTypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RPT_TODAYS_TOTAL_DOCUMENTS_REGISTERED_SUMMARY_Result>("USP_RPT_TODAYS_TOTAL_DOCUMENTS_REGISTERED_SUMMARY", dISTRICTCODEParameter, sROCodeParameter, fromDateParameter, toDateParameter, isDROParameter, documentTypeIDParameter);
        }
    }
}
