//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaigrSearchDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_ProcessingIterationMaster
    {
        public int IterationID { get; set; }
        public bool IsDro { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public bool IsValid { get; set; }
    }
}
