//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_RefundChallanUsageDetails
    {
        public long Id { get; set; }
        public long RowId { get; set; }
        public string ChallanPurposeDescription { get; set; }
        public int FeeRuleCode { get; set; }
    
        public virtual FeesRuleMaster FeesRuleMaster { get; set; }
        public virtual AMS_RefundChallanDetails AMS_RefundChallanDetails { get; set; }
    }
}
