//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_REG_KhajaneExceptionLog
    {
        public long Logid { get; set; }
        public int SROCode { get; set; }
        public string ExceptionType { get; set; }
        public string InnerExceptionMsg { get; set; }
        public string ExceptionMsg { get; set; }
        public string ExceptionStackTrace { get; set; }
        public string ExceptionMethodName { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<bool> IsDRO { get; set; }
        public Nullable<int> DRO { get; set; }
    
        public virtual SROMaster SROMaster { get; set; }
    }
}
