//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_BankTransactionAmountDetails
    {
        public long ID { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> FeesRuleCode { get; set; }
        public Nullable<byte> AccountHeadID { get; set; }
        public Nullable<int> Srocode { get; set; }
        public Nullable<int> DeptSubPurposeID { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<int> AreaTypeID { get; set; }
    
        public virtual FeesRuleMaster FeesRuleMaster { get; set; }
    }
}
