//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_ChallanMatrixDetails
    {
        public long ChallanID { get; set; }
        public long ChallanRequestID { get; set; }
        public string BatchID { get; set; }
        public System.DateTime ChallanDate { get; set; }
        public System.DateTime ChallanExpiryDate { get; set; }
        public decimal ChallanTotalAmount { get; set; }
        public string PaymentMode { get; set; }
        public decimal ChallanAmount { get; set; }
        public string CCNumber { get; set; }
        public string CardType { get; set; }
        public Nullable<System.DateTime> InstrmntDate { get; set; }
        public string InstrmntNumber { get; set; }
        public string MICRCode { get; set; }
        public string RemitterName { get; set; }
        public string RmtncAgencyBank { get; set; }
        public string ChallanRefNum { get; set; }
        public string DepartmentRefNumber { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
    
        public virtual AMS_ChallanMatrixTransDetails AMS_ChallanMatrixTransDetails { get; set; }
    }
}
