//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_ChallanMatrixTransDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AMS_ChallanMatrixTransDetails()
        {
            this.AMS_ChallanMatrixDetails = new HashSet<AMS_ChallanMatrixDetails>();
        }
    
        public long ChallanRequestID { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public Nullable<int> SroCode { get; set; }
        public string DDOCode { get; set; }
        public string RemittanceBankName { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string UIRNumber { get; set; }
        public Nullable<bool> TransactionStatus { get; set; }
        public string StatusCode { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<long> UserID { get; set; }
        public string IPAdd { get; set; }
        public string BatchID { get; set; }
        public Nullable<System.DateTime> FirstPrintdate { get; set; }
        public string RequestPaymentMode { get; set; }
        public bool IsDRO { get; set; }
        public Nullable<int> DROCode { get; set; }
        public Nullable<long> SchedulerID { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_ChallanMatrixDetails> AMS_ChallanMatrixDetails { get; set; }
        public virtual AMS_ChallanMatrixTransDetails AMS_ChallanMatrixTransDetails1 { get; set; }
        public virtual AMS_ChallanMatrixTransDetails AMS_ChallanMatrixTransDetails2 { get; set; }
        public virtual SROMaster SROMaster { get; set; }
    }
}
