//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMS_RefundChallanDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AMS_RefundChallanDetails()
        {
            this.AMS_RefundChallanUsageDetails = new HashSet<AMS_RefundChallanUsageDetails>();
        }
    
        public long RowId { get; set; }
        public string InstrumentNumber { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
        public Nullable<int> SROCode { get; set; }
        public Nullable<int> DROCode { get; set; }
        public Nullable<bool> IsDRApproved { get; set; }
        public Nullable<System.DateTime> ApplicationDateTime { get; set; }
        public Nullable<decimal> ChallanAmount { get; set; }
        public string PartyName { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<long> SROUserId { get; set; }
        public Nullable<long> DROUserId { get; set; }
        public Nullable<System.DateTime> ApproveDateTime { get; set; }
        public string PartyMobileNumber { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public bool IsFinalized { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public string AbsoluteFilePath { get; set; }
        public string Relativepath { get; set; }
        public string FileName { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual UMG_UserDetails UMG_UserDetails { get; set; }
        public virtual UMG_UserDetails UMG_UserDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_RefundChallanUsageDetails> AMS_RefundChallanUsageDetails { get; set; }
    }
}
