//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BhoomiMappingDetails
    {
        public double BhoomiMappingID { get; set; }
        public Nullable<double> DistrictCode { get; set; }
        public string DistrictNameE { get; set; }
        public Nullable<double> KaveriSROCode { get; set; }
        public string KaveriSROName { get; set; }
        public Nullable<double> KaveriVillageCode { get; set; }
        public string KaveriVillageName { get; set; }
        public Nullable<double> KaveriHobiCode { get; set; }
        public string KaveriHobiName { get; set; }
        public Nullable<double> BhoomiDistrictCode { get; set; }
        public Nullable<double> BhoomiTalukCode { get; set; }
        public string BhoomiTalukName { get; set; }
        public Nullable<double> BhoomiHobiCode { get; set; }
        public string BhoomiHobiName { get; set; }
        public Nullable<double> BhoomiVillageCode { get; set; }
        public string BhoomiVillageName { get; set; }
        public bool IsUpdated { get; set; }
    }
}
