//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockchainRequestDetails
    {
        public long RequestID { get; set; }
        public long DocumentID { get; set; }
        public int SROCode { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int ReasonID { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
    
        public virtual BlockchainReasonDetails BlockchainReasonDetails { get; set; }
        public virtual DocumentMaster DocumentMaster { get; set; }
    }
}
