//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMN_System_User_ActivityLog
    {
        public int ActivityID { get; set; }
        public long UserID { get; set; }
        public int ActivityTypeID { get; set; }
        public string LogDesc { get; set; }
    
        public virtual MAS_ActivityType MAS_ActivityType { get; set; }
        public virtual UMG_UserDetails UMG_UserDetails { get; set; }
    }
}
