//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMN_AuditMvcEventLoging
    {
        public long AuditID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string UrlAccessed { get; set; }
        public string IPAddress { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public Nullable<short> ServiceID { get; set; }
    
        public virtual MAS_ServiceMaster MAS_ServiceMaster { get; set; }
        public virtual UMG_UserDetails UMG_UserDetails { get; set; }
    }
}
