//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RES_TABLE_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DB_RES_TABLE_MASTER()
        {
            this.DB_RES_TABLEWISE_COUNT = new HashSet<DB_RES_TABLEWISE_COUNT>();
        }
    
        public int TABLE_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public bool IS_INCLUDED { get; set; }
        public int MODULE_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DB_RES_TABLEWISE_COUNT> DB_RES_TABLEWISE_COUNT { get; set; }
    }
}
