//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RES_TABLEWISE_COUNT
    {
        public int ROWID { get; set; }
        public int INIT_ID { get; set; }
        public int TABLE_ID { get; set; }
        public Nullable<int> ROWS_TO_BE_INSERTED { get; set; }
        public Nullable<int> ROWS_INSERTED { get; set; }
    
        public virtual DB_RES_INITIATE_MASTER DB_RES_INITIATE_MASTER { get; set; }
        public virtual DB_RES_TABLE_MASTER DB_RES_TABLE_MASTER { get; set; }
    }
}
