//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RES_ACTIONS
    {
        public int ROW_ID { get; set; }
        public Nullable<int> INIT_ID { get; set; }
        public Nullable<int> ACTION_ID { get; set; }
        public System.DateTime ACTION_DATETIME { get; set; }
        public bool IS_SUCCESSFUL { get; set; }
        public Nullable<int> SCRIPT_ID { get; set; }
        public string ERROR_DESCRIPTION { get; set; }
        public string CORRECTIVEACTION { get; set; }
    
        public virtual DB_RES_ACTIONS_MASTER DB_RES_ACTIONS_MASTER { get; set; }
        public virtual DB_RES_INITIATE_MASTER DB_RES_INITIATE_MASTER { get; set; }
        public virtual DB_RES_INSERT_SCRIPT_DETAILS DB_RES_INSERT_SCRIPT_DETAILS { get; set; }
    }
}
