//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RES_ACTIONS_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DB_RES_ACTIONS_MASTER()
        {
            this.DB_RES_ACTIONS = new HashSet<DB_RES_ACTIONS>();
        }
    
        public int ACTION_ID { get; set; }
        public string ACTION_DESCRIPTION { get; set; }
        public bool IS_ACTIVE { get; set; }
        public int ACTION_EXECUTION_SEQUENCE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DB_RES_ACTIONS> DB_RES_ACTIONS { get; set; }
    }
}
