//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RES_SERVICE_COMM_DETAILS
    {
        public int ROWID { get; set; }
        public string SERVICE_TYPE { get; set; }
        public int INIT_ID { get; set; }
        public string KEY_COLUMN { get; set; }
        public string KEY_VALUE { get; set; }
    
        public virtual DB_RES_INITIATE_MASTER DB_RES_INITIATE_MASTER { get; set; }
    }
}
