//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_RES_ACTIVATION_KEY_OTP
    {
        public int KEYID { get; set; }
        public Nullable<int> INIT_ID { get; set; }
        public Nullable<int> KEY_TYPE { get; set; }
        public string KEYVALUE { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<System.DateTime> KEY_DATETIME { get; set; }
    
        public virtual DB_RES_INITIATE_MASTER DB_RES_INITIATE_MASTER { get; set; }
    }
}
