//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEC_DRPNDNote
    {
        public int NoteID { get; set; }
        public int OrderID { get; set; }
        public long PropertyID { get; set; }
        public string Note_PreparedPart { get; set; }
        public string Note_EnteredPart { get; set; }
        public long UserID { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime InsertDateTime { get; set; }
    
        public virtual DEC_DROrderMaster DEC_DROrderMaster { get; set; }
        public virtual UMG_UserDetails UMG_UserDetails { get; set; }
    }
}
