//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticMaster
    {
        public int DiagnosticId { get; set; }
        public int OfficeCode { get; set; }
        public System.DateTime DiagnosticDate { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> CompletionTime { get; set; }
        public string RequestIP { get; set; }
        public string LoginId { get; set; }
        public short IsSuccessful { get; set; }
        public bool IsCentralized { get; set; }
        public string SecureCode { get; set; }
        public int isDRO { get; set; }
        public int MasterID { get; set; }
    }
}
