//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticDetails
    {
        public int DetailId { get; set; }
        public int ActionId { get; set; }
        public bool ActionStatus { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<int> MasterID { get; set; }
        public string Dignostic_Output { get; set; }
    }
}
