//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECPropertySearchKeyValues
    {
        public long KeyID { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public long VillageCode { get; set; }
        public Nullable<long> PropertyID { get; set; }
        public Nullable<int> RegSROCode { get; set; }
        public Nullable<int> SROCode { get; set; }
        public long DocumentID { get; set; }
        public Nullable<long> NewPropertyID { get; set; }
        public Nullable<int> NewRegSROCode { get; set; }
        public Nullable<int> NewSROCode { get; set; }
        public int CurrentPropertyTypeID { get; set; }
        public string CurrentNumber { get; set; }
        public Nullable<int> OldPropertyTypeID { get; set; }
        public string OldNumber { get; set; }
        public Nullable<int> Survey_No { get; set; }
        public string Surnoc { get; set; }
        public string Hissa_No { get; set; }
        public Nullable<int> OrderID { get; set; }
        public int IsActivated { get; set; }
        public string ActionType { get; set; }
    
        public virtual DEC_DROrderMaster DEC_DROrderMaster { get; set; }
        public virtual DocumentMaster DocumentMaster { get; set; }
        public virtual PropertyMaster PropertyMaster { get; set; }
        public virtual PropertyNoTypeMaster PropertyNoTypeMaster { get; set; }
        public virtual PropertyNoTypeMaster PropertyNoTypeMaster1 { get; set; }
        public virtual VillageMaster VillageMaster { get; set; }
    }
}
