//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeesRuleMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeesRuleMaster()
        {
            this.AMS_BankTransactionAmountDetails = new HashSet<AMS_BankTransactionAmountDetails>();
            this.AMS_RefundChallanUsageDetails = new HashSet<AMS_RefundChallanUsageDetails>();
        }
    
        public int FeeRuleCode { get; set; }
        public int RegArticleCode { get; set; }
        public Nullable<short> SameAsArticleID { get; set; }
        public Nullable<short> ParentRefID { get; set; }
        public bool HasChild { get; set; }
        public string DescriptionK { get; set; }
        public string DescriptionE { get; set; }
        public bool IsSlabs { get; set; }
        public bool UnitIsAmount { get; set; }
        public string UnitDescriptionK { get; set; }
        public string UnitDescriptionE { get; set; }
        public double Unit { get; set; }
        public double Value { get; set; }
        public Nullable<decimal> MinLimit { get; set; }
        public Nullable<decimal> MaxLimit { get; set; }
        public Nullable<short> MultipliedBy { get; set; }
        public bool IsInPercentage { get; set; }
        public bool IsFixDuty { get; set; }
        public bool IsExempted { get; set; }
        public bool IsRuleActive { get; set; }
        public Nullable<int> StdSeqID { get; set; }
        public bool IsOther { get; set; }
        public short FeeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_BankTransactionAmountDetails> AMS_BankTransactionAmountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_RefundChallanUsageDetails> AMS_RefundChallanUsageDetails { get; set; }
    }
}
