//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmMaster
    {
        public decimal RegistrationID { get; set; }
        public string FirmNumber { get; set; }
        public string FirmName { get; set; }
        public string FirmAddress { get; set; }
        public string FirmPhone { get; set; }
        public int ParentRef { get; set; }
        public Nullable<bool> HasBranches { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
        public string SupportDocuments { get; set; }
        public Nullable<int> DurationOfFirm { get; set; }
        public string NameOfPresenter { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Fees { get; set; }
        public Nullable<int> AmendmentNo { get; set; }
        public string AmendmentDesc { get; set; }
        public Nullable<int> Pages { get; set; }
        public string Remarks { get; set; }
        public string OldName { get; set; }
        public Nullable<bool> PrintFlag { get; set; }
        public Nullable<long> ReceiptID { get; set; }
        public string OldAddress { get; set; }
        public Nullable<int> AtWill { get; set; }
        public string FirstName { get; set; }
        public string FirstAddress { get; set; }
        public Nullable<int> Nature { get; set; }
        public int DRCode { get; set; }
        public string FirmType { get; set; }
        public Nullable<int> IsScanned { get; set; }
        public string CDNumber { get; set; }
        public string OldFirmDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string PresenterMobile { get; set; }
    }
}
