//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmDataCentralizationDetails
    {
        public long RegistrationID { get; set; }
        public int DROCode { get; set; }
        public string FirmNumber { get; set; }
        public bool IsFirmDataCentralizaed { get; set; }
        public string CDNumber { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
        public Nullable<bool> IsScanDocumentUploaded { get; set; }
        public string ScanFileName { get; set; }
        public Nullable<long> CDID { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<System.DateTime> ScanDateTime { get; set; }
        public Nullable<decimal> Checksum { get; set; }
        public Nullable<bool> IsSakalaAccept { get; set; }
        public Nullable<bool> IsSAKALAUpdate { get; set; }
    }
}
