//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRUITSXML
    {
        public long LogId { get; set; }
        public int SROCode { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<long> DocumentID { get; set; }
        public byte ResponseStatus { get; set; }
        public string SentXMLDetails { get; set; }
        public bool IsUploaded { get; set; }
        public Nullable<System.DateTime> UploadDateTime { get; set; }
        public string AckxmlDetails { get; set; }
        public bool istransmitted { get; set; }
    }
}
