//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_SEVASINDHU_MAR_DATA_RECV_DETAILS
    {
        public long RequestID { get; set; }
        public string ReferenceNo { get; set; }
        public int SROCode { get; set; }
        public string TransXML { get; set; }
        public string AknowledgementNo { get; set; }
        public System.DateTime DataReceivedDate { get; set; }
        public System.DateTime AppointmentDateTime { get; set; }
        public string AppointmentSlot { get; set; }
        public bool IsApplicationRegistered { get; set; }
        public Nullable<System.DateTime> ApplicationRegistrationDateTime { get; set; }
        public string FinalRegistrationNumber { get; set; }
        public Nullable<long> RegistrationID { get; set; }
        public Nullable<long> NoticeID { get; set; }
        public Nullable<System.DateTime> ApplicationAcceptDateTime { get; set; }
        public Nullable<System.DateTime> ApplicationRejectDateTime { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<byte> ApplicationStatusCode { get; set; }
    }
}
