//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationDepartment
    {
        public int UDeptID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<bool> GetData { get; set; }
        public string WebServiceAddress { get; set; }
        public string RegistrationArticlesIds { get; set; }
        public string BookIds { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
