//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaveri2Pilot
    {
        public int RowID { get; set; }
        public int SROCode { get; set; }
        public System.DateTime PilotDate { get; set; }
        public string EnteredBy { get; set; }
        public int IsValid { get; set; }
    }
}
