//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarriageRegistration
    {
        public long RegistrationID { get; set; }
        public int PSROCode { get; set; }
        public string MarriageCaseNo { get; set; }
        public Nullable<int> MarriageTypeID { get; set; }
        public Nullable<long> Bride { get; set; }
        public Nullable<long> BrideGroom { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public int FeesReceived { get; set; }
        public Nullable<System.DateTime> HinduMarriageDate { get; set; }
        public byte[] CombinePhoto { get; set; }
        public Nullable<long> NoticeID { get; set; }
        public string CDNumber { get; set; }
        public Nullable<int> SROCode { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<int> IsScanned { get; set; }
        public string NameOfMarriageOfficer { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<bool> IsTransmitted { get; set; }
    
        public virtual MarriageScanDocVerifyLog MarriageScanDocVerifyLog { get; set; }
    }
}
