//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_OfficeTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_OfficeTypes()
        {
            this.MAS_OfficeMaster = new HashSet<MAS_OfficeMaster>();
            this.MAS_OfficeTypes1 = new HashSet<MAS_OfficeTypes>();
        }
    
        public short OfficeTypeID { get; set; }
        public string OfficeTypeDesc { get; set; }
        public string OfficeTypeDescR { get; set; }
        public string ShortName { get; set; }
        public string ShortNameR { get; set; }
        public Nullable<short> ParentOfficeTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAS_OfficeMaster> MAS_OfficeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAS_OfficeTypes> MAS_OfficeTypes1 { get; set; }
        public virtual MAS_OfficeTypes MAS_OfficeTypes2 { get; set; }
    }
}
