//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_Talukas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_Talukas()
        {
            this.MAS_OfficeMaster = new HashSet<MAS_OfficeMaster>();
            this.MAS_Villages = new HashSet<MAS_Villages>();
        }
    
        public short TalukaID { get; set; }
        public Nullable<short> OfficeID { get; set; }
        public string TalukaName { get; set; }
        public string TalukaNameR { get; set; }
        public string CensusCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAS_OfficeMaster> MAS_OfficeMaster { get; set; }
        public virtual MAS_OfficeMaster MAS_OfficeMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAS_Villages> MAS_Villages { get; set; }
    }
}
