//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_Districts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_Districts()
        {
            this.MAS_OfficeMaster = new HashSet<MAS_OfficeMaster>();
        }
    
        public short DistrictID { get; set; }
        public short StateID { get; set; }
        public string DistrictName { get; set; }
        public string DistrictNameR { get; set; }
        public string ShortName { get; set; }
        public string ShortNameR { get; set; }
        public string CensusCode { get; set; }
        public bool IsRevenueDistrict { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<System.DateTime> TestDateTime { get; set; }
        public Nullable<int> Kaveri1Code { get; set; }
    
        public virtual MAS_States MAS_States { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAS_OfficeMaster> MAS_OfficeMaster { get; set; }
    }
}
