//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_ServiceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_ServiceMaster()
        {
            this.AMS_Remittance_Office_Status = new HashSet<AMS_Remittance_Office_Status>();
            this.CMN_AuditApiLoging = new HashSet<CMN_AuditApiLoging>();
            this.CMN_AuditMvcEventLoging = new HashSet<CMN_AuditMvcEventLoging>();
            this.AMS_BankInstrumentNumberDetails = new HashSet<AMS_BankInstrumentNumberDetails>();
        }
    
        public short ServiceID { get; set; }
        public string ServiceName { get; set; }
        public string ServiceNameR { get; set; }
        public System.TimeSpan ServiceOpenTime { get; set; }
        public System.TimeSpan ServiceCloseTime { get; set; }
        public bool IsActive { get; set; }
        public bool IsOnline { get; set; }
        public string TriLetter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_Remittance_Office_Status> AMS_Remittance_Office_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMN_AuditApiLoging> CMN_AuditApiLoging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMN_AuditMvcEventLoging> CMN_AuditMvcEventLoging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_BankInstrumentNumberDetails> AMS_BankInstrumentNumberDetails { get; set; }
    }
}
