//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_OfficeMaster_DisableInfo
    {
        public short OfficeID { get; set; }
        public short OfficeTypeID { get; set; }
        public string OfficeName { get; set; }
        public int Kaveri1Code { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<System.DateTime> DisableDate { get; set; }
    }
}
