//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MojaniXML
    {
        public long LogId { get; set; }
        public long DocumentID { get; set; }
        public long PropertyID { get; set; }
        public string InputSketchDetails { get; set; }
        public string ReceivedXMLDetails { get; set; }
        public string ReceivedEncXMLDetails { get; set; }
        public Nullable<bool> Verified { get; set; }
        public bool IsUploaded { get; set; }
        public Nullable<System.DateTime> UploadDateTime { get; set; }
        public string AckxmlDetails { get; set; }
        public string AckNumber { get; set; }
        public string SentXMLDetails { get; set; }
        public Nullable<bool> IsFinalRegistration { get; set; }
        public int SROCode { get; set; }
    }
}
