//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeMaster
    {
        public long NoticeID { get; set; }
        public int PSROCode { get; set; }
        public string NoticeNo { get; set; }
        public System.DateTime NoticeIssuedDate { get; set; }
        public int Bride { get; set; }
        public int BrideGroom { get; set; }
        public Nullable<int> Fees { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> MarriageType { get; set; }
        public string CDNumber { get; set; }
        public Nullable<int> SROCode { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<int> IsScanned { get; set; }
        public Nullable<System.DateTime> dateofmarriage { get; set; }
        public Nullable<bool> IsSolamenised { get; set; }
        public Nullable<bool> IsTransmitted { get; set; }
    
        public virtual NoticeScanDocVerifyLog NoticeScanDocVerifyLog { get; set; }
    }
}
