//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineReceipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineReceipts()
        {
            this.ChallanNumberDataEntryCorrection = new HashSet<ChallanNumberDataEntryCorrection>();
        }
    
        public long ReceiptID { get; set; }
        public int SROCode { get; set; }
        public long ApplicationID { get; set; }
        public int ReceiptTypeID { get; set; }
        public long ReceiptNumber { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int PaymentMode { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public byte PurposeID { get; set; }
        public Nullable<decimal> ExemptedAmount { get; set; }
        public Nullable<decimal> TotalPaidAmount { get; set; }
        public string InsrumentNumber { get; set; }
        public Nullable<System.DateTime> InstrumentDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChallanNumberDataEntryCorrection> ChallanNumberDataEntryCorrection { get; set; }
        public virtual SROMaster SROMaster { get; set; }
    }
}
