//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoThumbUploadStatus
    {
        public long StatusID { get; set; }
        public long PartyID { get; set; }
        public int SROCode { get; set; }
        public Nullable<bool> isPhotoUploaded { get; set; }
        public Nullable<bool> isThumbUploaded { get; set; }
    
        public virtual PartyInfo PartyInfo { get; set; }
    }
}
