//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoThumbCD_Failed
    {
        public long ID { get; set; }
        public long LogID { get; set; }
        public Nullable<bool> IsPhoto { get; set; }
        public Nullable<bool> IsThumb { get; set; }
        public Nullable<long> PartyID { get; set; }
        public string Error { get; set; }
        public Nullable<int> SROCode { get; set; }
    
        public virtual PartyInfo PartyInfo { get; set; }
        public virtual PhotoThumbUploadLog PhotoThumbUploadLog { get; set; }
    }
}
