//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoThumbUploadLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhotoThumbUploadLog()
        {
            this.PhotoThumbCD_Failed = new HashSet<PhotoThumbCD_Failed>();
            this.PhotoThumbCD_Success = new HashSet<PhotoThumbCD_Success>();
        }
    
        public long LogID { get; set; }
        public string CDNumber { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> PhotoCount { get; set; }
        public Nullable<int> ThumbCount { get; set; }
        public Nullable<int> PhotosUploaded { get; set; }
        public Nullable<int> ThumbUploaded { get; set; }
        public Nullable<int> SROCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoThumbCD_Failed> PhotoThumbCD_Failed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoThumbCD_Success> PhotoThumbCD_Success { get; set; }
        public virtual SROMaster SROMaster { get; set; }
    }
}
