//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoThumbUploadDetails
    {
        public long UploadID { get; set; }
        public long DocumentID { get; set; }
        public long PartyID { get; set; }
        public bool IsPhoto { get; set; }
        public bool IsThumb { get; set; }
        public int SROCode { get; set; }
        public string Filename { get; set; }
        public string UploadPath { get; set; }
        public System.DateTime UploadDateTime { get; set; }
        public string RootDirectory { get; set; }
        public bool isUploadedFromCD { get; set; }
    
        public virtual DocumentMaster DocumentMaster { get; set; }
        public virtual PartyInfo PartyInfo { get; set; }
    }
}
