//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyMaster()
        {
            this.ECPropertySearchKeyValues = new HashSet<ECPropertySearchKeyValues>();
        }
    
        public long PropertyID { get; set; }
        public long DocumentID { get; set; }
        public long VillageCode { get; set; }
        public int RegSROCode { get; set; }
        public int SROCode { get; set; }
        public decimal TotalArea { get; set; }
        public int UnitID { get; set; }
        public string NorthBoundary { get; set; }
        public string SouthBoundary { get; set; }
        public string EastBoundary { get; set; }
        public string WestBoundary { get; set; }
        public string LandMark { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
        public string Assessment { get; set; }
        public string SDCalculationString { get; set; }
        public Nullable<decimal> StampDuty { get; set; }
        public short TransferLiabilities { get; set; }
        public decimal Consideration { get; set; }
        public decimal AdditionalDuty { get; set; }
        public decimal CESSDuty { get; set; }
        public decimal GovtDuty { get; set; }
        public bool IsExempted { get; set; }
        public string ExemptionDescription { get; set; }
        public bool IsMovableProperty { get; set; }
        public Nullable<decimal> SDRefund { get; set; }
        public Nullable<decimal> DocMarketValue { get; set; }
        public Nullable<long> ValID { get; set; }
        public Nullable<bool> IsImdemnified { get; set; }
        public string Restriction { get; set; }
        public string RestrictionType { get; set; }
        public string RestrictionDescription { get; set; }
        public string C11ENumber { get; set; }
        public string ClaimingBlockNumber { get; set; }
        public string RetainingBlockNumber { get; set; }
        public string ValuationReport { get; set; }
        public Nullable<short> LoanPurposeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECPropertySearchKeyValues> ECPropertySearchKeyValues { get; set; }
    }
}
