//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyNoTypeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyNoTypeMaster()
        {
            this.ECPropertySearchKeyValues = new HashSet<ECPropertySearchKeyValues>();
            this.ECPropertySearchKeyValues1 = new HashSet<ECPropertySearchKeyValues>();
        }
    
        public int PropertyTypeID { get; set; }
        public string TypeNameKannada { get; set; }
        public string TypeNameEnglish { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECPropertySearchKeyValues> ECPropertySearchKeyValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ECPropertySearchKeyValues> ECPropertySearchKeyValues1 { get; set; }
    }
}
