//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptPaymentDetails
    {
        public long ReceiptID { get; set; }
        public int SROCode { get; set; }
        public int PaymentModeID { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string DDNumber { get; set; }
        public Nullable<System.DateTime> DDdate { get; set; }
        public Nullable<int> IFSCCodeID { get; set; }
        public string IFSCCode { get; set; }
        public Nullable<decimal> MICRCode { get; set; }
    }
}
