//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceMaster
    {
        public int RefId { get; set; }
        public long DocumentID { get; set; }
        public long SROCode { get; set; }
        public Nullable<int> TrID { get; set; }
        public Nullable<int> ThroughID { get; set; }
        public string ReferenceText { get; set; }
        public string RevenueOfficerNo { get; set; }
        public string Court_No { get; set; }
        public Nullable<System.DateTime> RevenueDate { get; set; }
        public Nullable<System.DateTime> CourtDate { get; set; }
        public Nullable<short> DocumentTypeID { get; set; }
        public Nullable<long> RegistrationID { get; set; }
        public Nullable<long> NoticeID { get; set; }
        public Nullable<bool> istransmitted { get; set; }
    }
}
