//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_EC_KaveriPortal_UserMapping
    {
        public int RowId { get; set; }
        public int AnywhereECUserID { get; set; }
        public long KaveriPortalUserID { get; set; }
    
        public virtual REG_Users REG_Users { get; set; }
        public virtual UMG_UserDetails UMG_UserDetails { get; set; }
    }
}
