//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REG_Users()
        {
            this.REG_EC_KaveriPortal_UserMapping = new HashSet<REG_EC_KaveriPortal_UserMapping>();
        }
    
        public int UserId { get; set; }
        public Nullable<int> SROCode { get; set; }
        public string FullName { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string PrevPassword { get; set; }
        public bool OfficeAdmin { get; set; }
        public byte[] ThumbImage { get; set; }
        public byte[] Thumb1 { get; set; }
        public byte[] Thumb2 { get; set; }
        public Nullable<bool> BiometricRequired { get; set; }
        public byte DesignationId { get; set; }
        public Nullable<System.DateTime> PasswordChangeDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public short RoleID { get; set; }
        public bool HasCustomPermissions { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> DistrictCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REG_EC_KaveriPortal_UserMapping> REG_EC_KaveriPortal_UserMapping { get; set; }
    }
}
