//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationArticles
    {
        public int RegArticleCode { get; set; }
        public string ArticleNameK { get; set; }
        public string ArticleNameE { get; set; }
        public string UserArticleNo { get; set; }
        public Nullable<int> BookId { get; set; }
        public bool GetBhoomidata { get; set; }
    
        public virtual BookTypeMaster BookTypeMaster { get; set; }
    }
}
