//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_DocReg_NoCLBatchDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RPT_DocReg_NoCLBatchDetails()
        {
            this.RPT_DocReg_NoCLDetails = new HashSet<RPT_DocReg_NoCLDetails>();
            this.RPT_PropertyAreaDetails = new HashSet<RPT_PropertyAreaDetails>();
        }
    
        public long BatchID { get; set; }
        public Nullable<int> SROCode { get; set; }
        public Nullable<long> FromDocumentID { get; set; }
        public Nullable<long> ToDocumentID { get; set; }
        public Nullable<short> DocumentTypeID { get; set; }
        public System.DateTime BatchDateTime { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsMismatchFound { get; set; }
    
        public virtual SROMaster SROMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPT_DocReg_NoCLDetails> RPT_DocReg_NoCLDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPT_PropertyAreaDetails> RPT_PropertyAreaDetails { get; set; }
    }
}
