//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_PropertyAreaDetails
    {
        public long PropertyID { get; set; }
        public int SROCode { get; set; }
        public Nullable<int> VillageCode { get; set; }
        public Nullable<decimal> TotalArea { get; set; }
        public Nullable<int> MeasurementUnit { get; set; }
        public Nullable<long> DocumentID { get; set; }
        public Nullable<long> BatchID { get; set; }
        public Nullable<long> C_PropertyID { get; set; }
        public Nullable<int> C_SROCode { get; set; }
        public Nullable<int> C_VillageCode { get; set; }
        public Nullable<decimal> C_TotalArea { get; set; }
        public Nullable<long> C_DocumentID { get; set; }
        public Nullable<int> C_MeasurementUnit { get; set; }
        public string ErrorType { get; set; }
    
        public virtual RPT_DocReg_NoCLBatchDetails RPT_DocReg_NoCLBatchDetails { get; set; }
    }
}
