//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_DocReg_DateDetails
    {
        public long ID { get; set; }
        public long DocumentID { get; set; }
        public int SROCode { get; set; }
        public string TableName { get; set; }
        public Nullable<long> ReceiptID { get; set; }
        public Nullable<System.DateTime> L_DateOfReceipt { get; set; }
        public Nullable<System.DateTime> C_DateOfReceipt { get; set; }
        public Nullable<long> StampDetailsID { get; set; }
        public Nullable<System.DateTime> L_DateOfStamp { get; set; }
        public Nullable<System.DateTime> C_DateOfStamp { get; set; }
        public Nullable<System.DateTime> L_DDChalDate { get; set; }
        public Nullable<System.DateTime> C_DDChalDate { get; set; }
        public Nullable<System.DateTime> L_StampPaymentDate { get; set; }
        public Nullable<System.DateTime> C_StampPaymentDate { get; set; }
        public Nullable<System.DateTime> L_DateOfReturn { get; set; }
        public Nullable<System.DateTime> C_DateOfReturn { get; set; }
        public Nullable<long> PartyID { get; set; }
        public Nullable<System.DateTime> L_AdmissionDate { get; set; }
        public Nullable<System.DateTime> C_AdmissionDate { get; set; }
        public Nullable<long> BatchID { get; set; }
        public string ErrorType { get; set; }
    }
}
