//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScannedFileDownloadLog
    {
        public int LogID { get; set; }
        public Nullable<int> SROCode { get; set; }
        public string FRN { get; set; }
        public string FileName { get; set; }
        public string Filepath { get; set; }
        public string DownloadReason { get; set; }
        public Nullable<System.DateTime> DownloadDateTime { get; set; }
        public string SROName { get; set; }
        public long UserID { get; set; }
        public Nullable<byte> DocumentTypeID { get; set; }
        public Nullable<byte> ReasonID { get; set; }
    
        public virtual MAS_EnclosureDownloadReasons MAS_EnclosureDownloadReasons { get; set; }
        public virtual UMG_UserDetails UMG_UserDetails { get; set; }
    }
}
