//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScannedFileUploadDetails
    {
        public long DocumentID { get; set; }
        public int SROCode { get; set; }
        public string ScannedFileName { get; set; }
        public string UploadPath { get; set; }
        public System.DateTime UploadDateTime { get; set; }
        public string RootDirectory { get; set; }
        public int DocumentTypeID { get; set; }
    }
}
