//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanMaster
    {
        public long DocumentID { get; set; }
        public int SROCode { get; set; }
        public int DocumentTypeID { get; set; }
        public Nullable<int> Pages { get; set; }
        public string LocalPath { get; set; }
        public string BackupPath { get; set; }
        public string FileName { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<System.DateTime> ScanDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> CDID { get; set; }
        public Nullable<decimal> Checksum { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<bool> IsUploaded { get; set; }
        public Nullable<bool> istransmitted { get; set; }
    }
}
