//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePackDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicePackDetails()
        {
            this.ServicePackChangesDetails = new HashSet<ServicePackChangesDetails>();
            this.ServicePackReleaseDetails = new HashSet<ServicePackReleaseDetails>();
        }
    
        public int SpID { get; set; }
        public short TypeID { get; set; }
        public Nullable<bool> TestOrFinal { get; set; }
        public int Major { get; set; }
        public int Minor { get; set; }
        public string Description { get; set; }
        public string InstallationProcedure { get; set; }
        public string FileServerFPath { get; set; }
        public string FileServerVPath { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ServicePackAddedDateTime { get; set; }
        public Nullable<System.DateTime> ServicePackReleaseDateTime { get; set; }
        public bool IsReleased { get; set; }
        public Nullable<long> ServicePackUploadedBy { get; set; }
        public Nullable<long> ServicePackReleasedBy { get; set; }
        public Nullable<long> ServicePackIntegratedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePackChangesDetails> ServicePackChangesDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePackReleaseDetails> ServicePackReleaseDetails { get; set; }
        public virtual SoftwareReleaseType SoftwareReleaseType { get; set; }
        public virtual UMG_UserDetails UMG_UserDetails { get; set; }
        public virtual UMG_UserDetails UMG_UserDetails1 { get; set; }
        public virtual UMG_UserDetails UMG_UserDetails2 { get; set; }
    }
}
