//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocietyFirmCDMaster
    {
        public int CDID { get; set; }
        public Nullable<bool> IsSociety { get; set; }
        public string VolumeName { get; set; }
        public Nullable<System.DateTime> CDWriteDate { get; set; }
        public Nullable<int> TotalDocuments { get; set; }
        public Nullable<int> TotalPages { get; set; }
        public Nullable<int> TotalSize { get; set; }
        public Nullable<int> Copies { get; set; }
        public int DRCode { get; set; }
    }
}
