//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SROMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SROMaster()
        {
            this.AMS_ChallanMatrixTransDetails = new HashSet<AMS_ChallanMatrixTransDetails>();
            this.AMS_REG_KhajaneExceptionLog = new HashSet<AMS_REG_KhajaneExceptionLog>();
            this.AMS_Remittance_Office_Status = new HashSet<AMS_Remittance_Office_Status>();
            this.AppVersion = new HashSet<AppVersion>();
            this.DEC_DROrderMaster = new HashSet<DEC_DROrderMaster>();
            this.ARegisterFileDetails = new HashSet<ARegisterFileDetails>();
            this.ARegisterFileDetails1 = new HashSet<ARegisterFileDetails>();
            this.ARegisterGenerationDetails = new HashSet<ARegisterGenerationDetails>();
            this.PhotoThumbUploadLog = new HashSet<PhotoThumbUploadLog>();
            this.RPT_DocReg_NoCLBatchDetails = new HashSet<RPT_DocReg_NoCLBatchDetails>();
            this.SROBifurcationTriLetterDetails = new HashSet<SROBifurcationTriLetterDetails>();
            this.AMS_BankInstrumentNumberDetails = new HashSet<AMS_BankInstrumentNumberDetails>();
            this.ChallanNumberDataEntryCorrection = new HashSet<ChallanNumberDataEntryCorrection>();
            this.OnlineReceipts = new HashSet<OnlineReceipts>();
            this.VillageMasterVillagesMergingMapping = new HashSet<VillageMasterVillagesMergingMapping>();
        }
    
        public int SROCode { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public string SRONameK { get; set; }
        public string SRONameE { get; set; }
        public string ShortnameK { get; set; }
        public string ShortNameE { get; set; }
        public bool GetBhoomiData { get; set; }
        public Nullable<bool> IsVillageMatching { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_ChallanMatrixTransDetails> AMS_ChallanMatrixTransDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_REG_KhajaneExceptionLog> AMS_REG_KhajaneExceptionLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_Remittance_Office_Status> AMS_Remittance_Office_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppVersion> AppVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEC_DROrderMaster> DEC_DROrderMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARegisterFileDetails> ARegisterFileDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARegisterFileDetails> ARegisterFileDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARegisterGenerationDetails> ARegisterGenerationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoThumbUploadLog> PhotoThumbUploadLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPT_DocReg_NoCLBatchDetails> RPT_DocReg_NoCLBatchDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SROBifurcationTriLetterDetails> SROBifurcationTriLetterDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_BankInstrumentNumberDetails> AMS_BankInstrumentNumberDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChallanNumberDataEntryCorrection> ChallanNumberDataEntryCorrection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineReceipts> OnlineReceipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VillageMasterVillagesMergingMapping> VillageMasterVillagesMergingMapping { get; set; }
    }
}
