//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORAGE_SERVERDETAILS
    {
        public int ROWID { get; set; }
        public int SERVERID { get; set; }
        public string DRIVENAME { get; set; }
        public string DRIVETYPE { get; set; }
        public string FILE_SYSTEM { get; set; }
        public string TOTAL_SPACE { get; set; }
        public string FREE_SPACE { get; set; }
        public Nullable<System.DateTime> CAPTURE_DATE { get; set; }
    
        public virtual STORAGE_SERVERMASTER STORAGE_SERVERMASTER { get; set; }
    }
}
