//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORAGE_SERVERMASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STORAGE_SERVERMASTER()
        {
            this.STORAGE_SERVERDETAILS = new HashSet<STORAGE_SERVERDETAILS>();
        }
    
        public int SERVERID { get; set; }
        public string SERVERTYPE { get; set; }
        public string IPADDRESS { get; set; }
        public string DESCRIPTION { get; set; }
        public bool IS_CONSIDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORAGE_SERVERDETAILS> STORAGE_SERVERDETAILS { get; set; }
    }
}
