//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMG_ControllerActionDetails_Log
    {
        public long LogID { get; set; }
        public int CAID { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<long> UserID { get; set; }
        public string UserIPAddress { get; set; }
        public string ActionPerformed { get; set; }
    
        public virtual UMG_UserDetails UMG_UserDetails { get; set; }
    }
}
