//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMG_OTP_VerificationDetails
    {
        public long OtpVerificationID { get; set; }
        public long UserId { get; set; }
        public string OTPToSend { get; set; }
        public System.DateTime OTPSentDateTime { get; set; }
        public Nullable<bool> IsOTPVerified { get; set; }
        public Nullable<System.DateTime> OTPVerifiedDateTime { get; set; }
        public short OtpTypeId { get; set; }
        public Nullable<bool> IsNullfied { get; set; }
    
        public virtual UMG_UserDetails UMG_UserDetails { get; set; }
    }
}
