//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMG_ControllerActionDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UMG_ControllerActionDetails()
        {
            this.UMG_MenuActionAuthorizationMapping = new HashSet<UMG_MenuActionAuthorizationMapping>();
            this.UMG_MenuActionMapping = new HashSet<UMG_MenuActionMapping>();
            this.UMG_RoleActionAuth = new HashSet<UMG_RoleActionAuth>();
        }
    
        public int CAID { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsForMenuActionMapping { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_MenuActionAuthorizationMapping> UMG_MenuActionAuthorizationMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_MenuActionMapping> UMG_MenuActionMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_RoleActionAuth> UMG_RoleActionAuth { get; set; }
    }
}
