//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMG_UserDetails_Log
    {
        public long LogID { get; set; }
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public short DefaultRoleID { get; set; }
        public short LevelID { get; set; }
        public short OfficeID { get; set; }
        public bool IsActive { get; set; }
        public bool IsLocked { get; set; }
        public bool IsFirstLoginDone { get; set; }
        public Nullable<byte> FailedPasswordAttempts { get; set; }
        public Nullable<System.DateTime> PasswordChangeDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Remarks { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public Nullable<long> UserIDLog { get; set; }
        public string UserIPAddress { get; set; }
        public string ActionPerformed { get; set; }
    
        public virtual MAS_OfficeMaster MAS_OfficeMaster { get; set; }
        public virtual UMG_LevelDetails UMG_LevelDetails { get; set; }
        public virtual UMG_RoleDetails UMG_RoleDetails { get; set; }
    }
}
