//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KaveriEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMG_UserDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UMG_UserDetails()
        {
            this.CMN_AuditMvcEventLoging = new HashSet<CMN_AuditMvcEventLoging>();
            this.CMN_System_User_ActivityLog = new HashSet<CMN_System_User_ActivityLog>();
            this.UMG_ControllerActionDetails_Log = new HashSet<UMG_ControllerActionDetails_Log>();
            this.UMG_MenuActionMapping_Log = new HashSet<UMG_MenuActionMapping_Log>();
            this.UMG_MenuDetails_Log = new HashSet<UMG_MenuDetails_Log>();
            this.UMG_OTP_VerificationDetails = new HashSet<UMG_OTP_VerificationDetails>();
            this.UMG_RoleActionAuth_Log = new HashSet<UMG_RoleActionAuth_Log>();
            this.UMG_RoleDetails_Log = new HashSet<UMG_RoleDetails_Log>();
            this.UMG_RoleMenuMapping_Log = new HashSet<UMG_RoleMenuMapping_Log>();
            this.UMG_UserProfile = new HashSet<UMG_UserProfile>();
            this.UMG_UserProfile_Log = new HashSet<UMG_UserProfile_Log>();
            this.REG_EC_KaveriPortal_UserMapping = new HashSet<REG_EC_KaveriPortal_UserMapping>();
            this.DEC_DROrderMaster = new HashSet<DEC_DROrderMaster>();
            this.DEC_DRPNDNote = new HashSet<DEC_DRPNDNote>();
            this.ServicePackDetails = new HashSet<ServicePackDetails>();
            this.ServicePackDetails1 = new HashSet<ServicePackDetails>();
            this.ServicePackDetails2 = new HashSet<ServicePackDetails>();
            this.ScannedFileDownloadLog = new HashSet<ScannedFileDownloadLog>();
            this.AMS_RefundChallanDetails = new HashSet<AMS_RefundChallanDetails>();
            this.AMS_RefundChallanDetails1 = new HashSet<AMS_RefundChallanDetails>();
            this.DocumentRescanDetails = new HashSet<DocumentRescanDetails>();
            this.MarriageRescanDetails = new HashSet<MarriageRescanDetails>();
            this.ChallanNumberDataEntryCorrection = new HashSet<ChallanNumberDataEntryCorrection>();
        }
    
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public short DefaultRoleID { get; set; }
        public short LevelID { get; set; }
        public short OfficeID { get; set; }
        public bool IsActive { get; set; }
        public bool IsLocked { get; set; }
        public bool IsFirstLoginDone { get; set; }
        public Nullable<byte> FailedPasswordAttempts { get; set; }
        public Nullable<System.DateTime> PasswordChangeDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMN_AuditMvcEventLoging> CMN_AuditMvcEventLoging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMN_System_User_ActivityLog> CMN_System_User_ActivityLog { get; set; }
        public virtual MAS_OfficeMaster MAS_OfficeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_ControllerActionDetails_Log> UMG_ControllerActionDetails_Log { get; set; }
        public virtual UMG_LevelDetails UMG_LevelDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_MenuActionMapping_Log> UMG_MenuActionMapping_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_MenuDetails_Log> UMG_MenuDetails_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_OTP_VerificationDetails> UMG_OTP_VerificationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_RoleActionAuth_Log> UMG_RoleActionAuth_Log { get; set; }
        public virtual UMG_RoleDetails UMG_RoleDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_RoleDetails_Log> UMG_RoleDetails_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_RoleMenuMapping_Log> UMG_RoleMenuMapping_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_UserProfile> UMG_UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UMG_UserProfile_Log> UMG_UserProfile_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REG_EC_KaveriPortal_UserMapping> REG_EC_KaveriPortal_UserMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEC_DROrderMaster> DEC_DROrderMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEC_DRPNDNote> DEC_DRPNDNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePackDetails> ServicePackDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePackDetails> ServicePackDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePackDetails> ServicePackDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScannedFileDownloadLog> ScannedFileDownloadLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_RefundChallanDetails> AMS_RefundChallanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMS_RefundChallanDetails> AMS_RefundChallanDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentRescanDetails> DocumentRescanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarriageRescanDetails> MarriageRescanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChallanNumberDataEntryCorrection> ChallanNumberDataEntryCorrection { get; set; }
    }
}
