//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.KAIGR_ONLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_Hoblis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_Hoblis()
        {
            this.MAS_Villages = new HashSet<MAS_Villages>();
        }
    
        public int HobliID { get; set; }
        public short TalukaID { get; set; }
        public string HobliName { get; set; }
        public string HobliNameR { get; set; }
        public Nullable<int> BhoomiHobliCode { get; set; }
        public string BhoomiHobliName { get; set; }
        public Nullable<int> BhoomiTalukCode { get; set; }
        public string BhoomiTalukName { get; set; }
        public Nullable<int> BhoomiDistrictCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAS_Villages> MAS_Villages { get; set; }
    }
}
