//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ECDataAPI.AnyWhereECApplicationServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AnyWhereECApplicationServicesSoap", Namespace="http://tempuri.org/")]
    public partial class AnyWhereECApplicationServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AnyWhereECApplicationServices_TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorDirectoryListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorFileDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFileContentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AnyWhereECApplicationServices() {
            this.Url = global::ECDataAPI.Properties.Settings.Default.ECDataAPI_AnyWhereECApplicationServices_AnyWhereECApplicationServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AnyWhereECApplicationServices_TestCompletedEventHandler AnyWhereECApplicationServices_TestCompleted;
        
        /// <remarks/>
        public event GetErrorDirectoryListCompletedEventHandler GetErrorDirectoryListCompleted;
        
        /// <remarks/>
        public event GetErrorFileDetailsCompletedEventHandler GetErrorFileDetailsCompleted;
        
        /// <remarks/>
        public event GetFileContentCompletedEventHandler GetFileContentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AnyWhereECApplicationServices_Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AnyWhereECApplicationServices_Test() {
            object[] results = this.Invoke("AnyWhereECApplicationServices_Test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AnyWhereECApplicationServices_TestAsync() {
            this.AnyWhereECApplicationServices_TestAsync(null);
        }
        
        /// <remarks/>
        public void AnyWhereECApplicationServices_TestAsync(object userState) {
            if ((this.AnyWhereECApplicationServices_TestOperationCompleted == null)) {
                this.AnyWhereECApplicationServices_TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAnyWhereECApplicationServices_TestOperationCompleted);
            }
            this.InvokeAsync("AnyWhereECApplicationServices_Test", new object[0], this.AnyWhereECApplicationServices_TestOperationCompleted, userState);
        }
        
        private void OnAnyWhereECApplicationServices_TestOperationCompleted(object arg) {
            if ((this.AnyWhereECApplicationServices_TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AnyWhereECApplicationServices_TestCompleted(this, new AnyWhereECApplicationServices_TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorDirectoryList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorDetailsResponseModel GetErrorDirectoryList(string ApplicationName) {
            object[] results = this.Invoke("GetErrorDirectoryList", new object[] {
                        ApplicationName});
            return ((ErrorDetailsResponseModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorDirectoryListAsync(string ApplicationName) {
            this.GetErrorDirectoryListAsync(ApplicationName, null);
        }
        
        /// <remarks/>
        public void GetErrorDirectoryListAsync(string ApplicationName, object userState) {
            if ((this.GetErrorDirectoryListOperationCompleted == null)) {
                this.GetErrorDirectoryListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorDirectoryListOperationCompleted);
            }
            this.InvokeAsync("GetErrorDirectoryList", new object[] {
                        ApplicationName}, this.GetErrorDirectoryListOperationCompleted, userState);
        }
        
        private void OnGetErrorDirectoryListOperationCompleted(object arg) {
            if ((this.GetErrorDirectoryListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorDirectoryListCompleted(this, new GetErrorDirectoryListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorFileDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorDetailsResponseModel GetErrorFileDetails(string sPath) {
            object[] results = this.Invoke("GetErrorFileDetails", new object[] {
                        sPath});
            return ((ErrorDetailsResponseModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorFileDetailsAsync(string sPath) {
            this.GetErrorFileDetailsAsync(sPath, null);
        }
        
        /// <remarks/>
        public void GetErrorFileDetailsAsync(string sPath, object userState) {
            if ((this.GetErrorFileDetailsOperationCompleted == null)) {
                this.GetErrorFileDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorFileDetailsOperationCompleted);
            }
            this.InvokeAsync("GetErrorFileDetails", new object[] {
                        sPath}, this.GetErrorFileDetailsOperationCompleted, userState);
        }
        
        private void OnGetErrorFileDetailsOperationCompleted(object arg) {
            if ((this.GetErrorFileDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorFileDetailsCompleted(this, new GetErrorFileDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFileContent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FileContentResponseModel GetFileContent(FileContentRequestModel reqModel) {
            object[] results = this.Invoke("GetFileContent", new object[] {
                        reqModel});
            return ((FileContentResponseModel)(results[0]));
        }
        
        /// <remarks/>
        public void GetFileContentAsync(FileContentRequestModel reqModel) {
            this.GetFileContentAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void GetFileContentAsync(FileContentRequestModel reqModel, object userState) {
            if ((this.GetFileContentOperationCompleted == null)) {
                this.GetFileContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFileContentOperationCompleted);
            }
            this.InvokeAsync("GetFileContent", new object[] {
                        reqModel}, this.GetFileContentOperationCompleted, userState);
        }
        
        private void OnGetFileContentOperationCompleted(object arg) {
            if ((this.GetFileContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFileContentCompleted(this, new GetFileContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorDetailsResponseModel {
        
        private DriveInformationModel[] driveInfoModelListField;
        
        private bool isErrorField;
        
        private string sErrorMsgField;
        
        private string[] directoryNameArrayField;
        
        private string[] fileNameArrayField;
        
        private ErrorDirectoryModel[] errorDirectoryListField;
        
        /// <remarks/>
        public DriveInformationModel[] DriveInfoModelList {
            get {
                return this.driveInfoModelListField;
            }
            set {
                this.driveInfoModelListField = value;
            }
        }
        
        /// <remarks/>
        public bool isError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        public string sErrorMsg {
            get {
                return this.sErrorMsgField;
            }
            set {
                this.sErrorMsgField = value;
            }
        }
        
        /// <remarks/>
        public string[] DirectoryNameArray {
            get {
                return this.directoryNameArrayField;
            }
            set {
                this.directoryNameArrayField = value;
            }
        }
        
        /// <remarks/>
        public string[] FileNameArray {
            get {
                return this.fileNameArrayField;
            }
            set {
                this.fileNameArrayField = value;
            }
        }
        
        /// <remarks/>
        public ErrorDirectoryModel[] ErrorDirectoryList {
            get {
                return this.errorDirectoryListField;
            }
            set {
                this.errorDirectoryListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DriveInformationModel {
        
        private string driveNameField;
        
        private string freeSpaceField;
        
        private string totalSpaceField;
        
        private string fileSystemField;
        
        private string freeSpacePercentageField;
        
        private string driveTypeField;
        
        /// <remarks/>
        public string DriveName {
            get {
                return this.driveNameField;
            }
            set {
                this.driveNameField = value;
            }
        }
        
        /// <remarks/>
        public string FreeSpace {
            get {
                return this.freeSpaceField;
            }
            set {
                this.freeSpaceField = value;
            }
        }
        
        /// <remarks/>
        public string TotalSpace {
            get {
                return this.totalSpaceField;
            }
            set {
                this.totalSpaceField = value;
            }
        }
        
        /// <remarks/>
        public string FileSystem {
            get {
                return this.fileSystemField;
            }
            set {
                this.fileSystemField = value;
            }
        }
        
        /// <remarks/>
        public string FreeSpacePercentage {
            get {
                return this.freeSpacePercentageField;
            }
            set {
                this.freeSpacePercentageField = value;
            }
        }
        
        /// <remarks/>
        public string DriveType {
            get {
                return this.driveTypeField;
            }
            set {
                this.driveTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileContentResponseModel {
        
        private bool isErrorField;
        
        private string sErrorMsgField;
        
        private string downloadFileNameField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        public bool isError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        public string sErrorMsg {
            get {
                return this.sErrorMsgField;
            }
            set {
                this.sErrorMsgField = value;
            }
        }
        
        /// <remarks/>
        public string DownloadFileName {
            get {
                return this.downloadFileNameField;
            }
            set {
                this.downloadFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileContentRequestModel {
        
        private bool isZipRequiredField;
        
        private string filePathField;
        
        /// <remarks/>
        public bool isZipRequired {
            get {
                return this.isZipRequiredField;
            }
            set {
                this.isZipRequiredField = value;
            }
        }
        
        /// <remarks/>
        public string FilePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorDirectoryModel {
        
        private string textField;
        
        private string valueField;
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AnyWhereECApplicationServices_TestCompletedEventHandler(object sender, AnyWhereECApplicationServices_TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AnyWhereECApplicationServices_TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AnyWhereECApplicationServices_TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetErrorDirectoryListCompletedEventHandler(object sender, GetErrorDirectoryListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorDirectoryListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorDirectoryListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorDetailsResponseModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorDetailsResponseModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetErrorFileDetailsCompletedEventHandler(object sender, GetErrorFileDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorFileDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorFileDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorDetailsResponseModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorDetailsResponseModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetFileContentCompletedEventHandler(object sender, GetFileContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFileContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFileContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FileContentResponseModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FileContentResponseModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591