//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.ECDATADOCS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ECDATA_DOCS_Entities : DbContext
    {
        public ECDATA_DOCS_Entities()
            : base("name=ECDATA_DOCS_Entities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 480;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ECLOG_FUNCTIONALITY_DEBUG_LOG> ECLOG_FUNCTIONALITY_DEBUG_LOG { get; set; }
        public virtual DbSet<ECLOG_FUNCTIONALITY_MASTER> ECLOG_FUNCTIONALITY_MASTER { get; set; }
        public virtual DbSet<MAS_SchedulerMaster> MAS_SchedulerMaster { get; set; }
        public virtual DbSet<SROCentralTransSchedularRuntimeDetails> SROCentralTransSchedularRuntimeDetails { get; set; }
        public virtual DbSet<XELAuditSpecificationDetail> XELAuditSpecificationDetail { get; set; }
        public virtual DbSet<XELReadJobDetails> XELReadJobDetails { get; set; }
        public virtual DbSet<XELSchedulersExceptionLog> XELSchedulersExceptionLog { get; set; }
        public virtual DbSet<XELTransmissionLog> XELTransmissionLog { get; set; }
    
        public virtual ObjectResult<USP_XEL_EXCEPTION_LOG_Result> USP_XEL_EXCEPTION_LOG(Nullable<int> srocode, Nullable<System.DateTime> frmDate, Nullable<System.DateTime> toDate, Nullable<bool> isDRO)
        {
            var srocodeParameter = srocode.HasValue ?
                new ObjectParameter("srocode", srocode) :
                new ObjectParameter("srocode", typeof(int));
    
            var frmDateParameter = frmDate.HasValue ?
                new ObjectParameter("frmDate", frmDate) :
                new ObjectParameter("frmDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var isDROParameter = isDRO.HasValue ?
                new ObjectParameter("isDRO", isDRO) :
                new ObjectParameter("isDRO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_XEL_EXCEPTION_LOG_Result>("USP_XEL_EXCEPTION_LOG", srocodeParameter, frmDateParameter, toDateParameter, isDROParameter);
        }
    
        public virtual ObjectResult<USP_XEL_TRANSMISSION_LOG_Result> USP_XEL_TRANSMISSION_LOG(Nullable<int> srocode, Nullable<System.DateTime> frmDate, Nullable<System.DateTime> toDate, Nullable<bool> isDRO)
        {
            var srocodeParameter = srocode.HasValue ?
                new ObjectParameter("srocode", srocode) :
                new ObjectParameter("srocode", typeof(int));
    
            var frmDateParameter = frmDate.HasValue ?
                new ObjectParameter("frmDate", frmDate) :
                new ObjectParameter("frmDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            var isDROParameter = isDRO.HasValue ?
                new ObjectParameter("isDRO", isDRO) :
                new ObjectParameter("isDRO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_XEL_TRANSMISSION_LOG_Result>("USP_XEL_TRANSMISSION_LOG", srocodeParameter, frmDateParameter, toDateParameter, isDROParameter);
        }
    
        public virtual ObjectResult<USP_XEL_FILE_COUNT_OFFICEWISE_Result> USP_XEL_FILE_COUNT_OFFICEWISE(Nullable<bool> isDRO)
        {
            var isDROParameter = isDRO.HasValue ?
                new ObjectParameter("isDRO", isDRO) :
                new ObjectParameter("isDRO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_XEL_FILE_COUNT_OFFICEWISE_Result>("USP_XEL_FILE_COUNT_OFFICEWISE", isDROParameter);
        }
    
        public virtual ObjectResult<USP_XEL_FILE_LIST_OFFICEWISE_Result> USP_XEL_FILE_LIST_OFFICEWISE(Nullable<int> srocode, Nullable<bool> isDRO)
        {
            var srocodeParameter = srocode.HasValue ?
                new ObjectParameter("srocode", srocode) :
                new ObjectParameter("srocode", typeof(int));
    
            var isDROParameter = isDRO.HasValue ?
                new ObjectParameter("isDRO", isDRO) :
                new ObjectParameter("isDRO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_XEL_FILE_LIST_OFFICEWISE_Result>("USP_XEL_FILE_LIST_OFFICEWISE", srocodeParameter, isDROParameter);
        }
    
        public virtual ObjectResult<string> USP_XEL_Files_RootDirPath_List_officewise(Nullable<bool> isDRO)
        {
            var isDROParameter = isDRO.HasValue ?
                new ObjectParameter("isDRO", isDRO) :
                new ObjectParameter("isDRO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_XEL_Files_RootDirPath_List_officewise", isDROParameter);
        }
    }
}
