//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.ECDATA_PENDOCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocPendingHistory_PENDOCS
    {
        public long DocumentID { get; set; }
        public int PendingReasonID { get; set; }
        public string Description { get; set; }
        public System.DateTime PendingDate { get; set; }
        public Nullable<bool> IsCleared { get; set; }
        public int SROCode { get; set; }
    
        public virtual DocumentMaster_PENDOCS DocumentMaster { get; set; }
        public virtual PendingReasonMaster_PENDOCS PendingReasonMaster { get; set; }
    }
}
