//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataAPI.Entity.ECDATA_PENDOCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingReasonMaster_PENDOCS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PendingReasonMaster_PENDOCS()
        {
            this.DocPendingHistory = new HashSet<DocPendingHistory_PENDOCS>();
        }
    
        public int PendingReasonID { get; set; }
        public string ReasonInKannada { get; set; }
        public string ReasonInEnglish { get; set; }
        public string DocumentStage { get; set; }
        public int Severity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocPendingHistory_PENDOCS> DocPendingHistory { get; set; }
    }
}
