//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace CustomModels.Models.MISReports.TransactionDetails
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TransactionDetails
    {

        private TransactionDetailsBankDetails bankDetailsField;

        private TransactionDetailsBhoomi_TransactionDetails[] bhoomi_LandParcelDetailsField;

        /// <remarks/>
        public TransactionDetailsBankDetails BankDetails
        {
            get
            {
                return this.bankDetailsField;
            }
            set
            {
                this.bankDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("bhoomi_TransactionDetails", IsNullable = false)]
        public TransactionDetailsBhoomi_TransactionDetails[] bhoomi_LandParcelDetails
        {
            get
            {
                return this.bhoomi_LandParcelDetailsField;
            }
            set
            {
                this.bhoomi_LandParcelDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TransactionDetailsBankDetails
    {

        private string nameofbankField;

        private string branchnameField;

        private string branchaddressField;

        private string branchMobilenumberField;

        private string branchEPICField;

        private string branchPANField;

        private TransactionDetailsBankDetailsTransactionType transactionTypeField;

        private decimal considerationamountField;

        /// <remarks/>
        public string nameofbank
        {
            get
            {
                return this.nameofbankField;
            }
            set
            {
                this.nameofbankField = value;
            }
        }

        /// <remarks/>
        public string branchname
        {
            get
            {
                return this.branchnameField;
            }
            set
            {
                this.branchnameField = value;
            }
        }

        /// <remarks/>
        public string branchaddress
        {
            get
            {
                return this.branchaddressField;
            }
            set
            {
                this.branchaddressField = value;
            }
        }

        /// <remarks/>
        public string branchMobilenumber
        {
            get
            {
                return this.branchMobilenumberField;
            }
            set
            {
                this.branchMobilenumberField = value;
            }
        }

        /// <remarks/>
        public string branchEPIC
        {
            get
            {
                return this.branchEPICField;
            }
            set
            {
                this.branchEPICField = value;
            }
        }

        /// <remarks/>
        public string branchPAN
        {
            get
            {
                return this.branchPANField;
            }
            set
            {
                this.branchPANField = value;
            }
        }

        /// <remarks/>
        public TransactionDetailsBankDetailsTransactionType TransactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }

        /// <remarks/>
        public decimal considerationamount
        {
            get
            {
                return this.considerationamountField;
            }
            set
            {
                this.considerationamountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum TransactionDetailsBankDetailsTransactionType
    {

        /// <remarks/>
        M,

        /// <remarks/>
        R,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TransactionDetailsBhoomi_TransactionDetails
    {

        private TransactionDetailsBhoomi_TransactionDetailsLandParcelDetails landParcelDetailsField;

        private TransactionDetailsBhoomi_TransactionDetailsOwnerdetails[] bhoomi_survey_ownersField;

        /// <remarks/>
        public TransactionDetailsBhoomi_TransactionDetailsLandParcelDetails LandParcelDetails
        {
            get
            {
                return this.landParcelDetailsField;
            }
            set
            {
                this.landParcelDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ownerdetails", IsNullable = false)]
        public TransactionDetailsBhoomi_TransactionDetailsOwnerdetails[] bhoomi_survey_owners
        {
            get
            {
                return this.bhoomi_survey_ownersField;
            }
            set
            {
                this.bhoomi_survey_ownersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TransactionDetailsBhoomi_TransactionDetailsLandParcelDetails
    {

        private uint bHOOMIdistrictcodeField;

        private uint talukacodeField;

        private uint hoblicodeField;

        private uint villagecodeField;

        private uint landcodeField;

        private uint surveynumberField;

        private string surveynumbercharacterField;

        private string hissanumberField;

        private TransactionDetailsBhoomi_TransactionDetailsLandParcelDetailsTransextents transextentsField;

        /// <remarks/>
        public uint BHOOMIdistrictcode
        {
            get
            {
                return this.bHOOMIdistrictcodeField;
            }
            set
            {
                this.bHOOMIdistrictcodeField = value;
            }
        }

        /// <remarks/>
        public uint talukacode
        {
            get
            {
                return this.talukacodeField;
            }
            set
            {
                this.talukacodeField = value;
            }
        }

        /// <remarks/>
        public uint hoblicode
        {
            get
            {
                return this.hoblicodeField;
            }
            set
            {
                this.hoblicodeField = value;
            }
        }

        /// <remarks/>
        public uint villagecode
        {
            get
            {
                return this.villagecodeField;
            }
            set
            {
                this.villagecodeField = value;
            }
        }

        /// <remarks/>
        public uint landcode
        {
            get
            {
                return this.landcodeField;
            }
            set
            {
                this.landcodeField = value;
            }
        }

        /// <remarks/>
        public uint surveynumber
        {
            get
            {
                return this.surveynumberField;
            }
            set
            {
                this.surveynumberField = value;
            }
        }

        /// <remarks/>
        public string surveynumbercharacter
        {
            get
            {
                return this.surveynumbercharacterField;
            }
            set
            {
                this.surveynumbercharacterField = value;
            }
        }

        /// <remarks/>
        public string hissanumber
        {
            get
            {
                return this.hissanumberField;
            }
            set
            {
                this.hissanumberField = value;
            }
        }

        /// <remarks/>
        public TransactionDetailsBhoomi_TransactionDetailsLandParcelDetailsTransextents transextents
        {
            get
            {
                return this.transextentsField;
            }
            set
            {
                this.transextentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TransactionDetailsBhoomi_TransactionDetailsLandParcelDetailsTransextents
    {

        private decimal ext_acreField;

        private decimal ext_guntaField;

        private decimal ext_fguntaField;

        /// <remarks/>
        public decimal ext_acre
        {
            get
            {
                return this.ext_acreField;
            }
            set
            {
                this.ext_acreField = value;
            }
        }

        /// <remarks/>
        public decimal ext_gunta
        {
            get
            {
                return this.ext_guntaField;
            }
            set
            {
                this.ext_guntaField = value;
            }
        }

        /// <remarks/>
        public decimal ext_fgunta
        {
            get
            {
                return this.ext_fguntaField;
            }
            set
            {
                this.ext_fguntaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TransactionDetailsBhoomi_TransactionDetailsOwnerdetails
    {

        private string nameField;

        private string addressField;

        private string mobilenumberField;

        private int bincomField;

        private string relativenameField;

        private uint ownernoField;

        private uint mainownernoField;

        private TransactionDetailsBhoomi_TransactionDetailsOwnerdetailsSex sexField;

        private byte ageField;

        private string ePICField;

        private string pANField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string mobilenumber
        {
            get
            {
                return this.mobilenumberField;
            }
            set
            {
                this.mobilenumberField = value;
            }
        }

        /// <remarks/>
        public int Bincom
        {
            get
            {
                return this.bincomField;
            }
            set
            {
                this.bincomField = value;
            }
        }

        /// <remarks/>
        public string relativename
        {
            get
            {
                return this.relativenameField;
            }
            set
            {
                this.relativenameField = value;
            }
        }

        /// <remarks/>
        public uint ownerno
        {
            get
            {
                return this.ownernoField;
            }
            set
            {
                this.ownernoField = value;
            }
        }

        /// <remarks/>
        public uint mainownerno
        {
            get
            {
                return this.mainownernoField;
            }
            set
            {
                this.mainownernoField = value;
            }
        }

        /// <remarks/>
        public TransactionDetailsBhoomi_TransactionDetailsOwnerdetailsSex sex
        {
            get
            {
                return this.sexField;
            }
            set
            {
                this.sexField = value;
            }
        }

        /// <remarks/>
        public byte age
        {
            get
            {
                return this.ageField;
            }
            set
            {
                this.ageField = value;
            }
        }

        /// <remarks/>
        public string EPIC
        {
            get
            {
                return this.ePICField;
            }
            set
            {
                this.ePICField = value;
            }
        }

        /// <remarks/>
        public string PAN
        {
            get
            {
                return this.pANField;
            }
            set
            {
                this.pANField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum TransactionDetailsBhoomi_TransactionDetailsOwnerdetailsSex
    {

        /// <remarks/>
        F,

        /// <remarks/>
        M,

        /// <remarks/>
        O,
    }
}
