//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECLOG_FUNCTIONALITY_DEBUG_LOG
    {
        public long DETAIL_ID { get; set; }
        public int FUNCTIONALITY_ID { get; set; }
        public string LOG_DESCRIPTION { get; set; }
        public System.DateTime INSERT_DATETIME { get; set; }
        public string CLASSNAME { get; set; }
        public string METHODNAME { get; set; }
    
        public virtual ECLOG_FUNCTIONALITY_MASTER ECLOG_FUNCTIONALITY_MASTER { get; set; }
    }
}
