//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SROCentralTransSchedularRuntimeDetails
    {
        public long IDetailID { get; set; }
        public int SROCode { get; set; }
        public string SROName { get; set; }
        public string SchedularRuntime { get; set; }
        public bool IsActive { get; set; }
    }
}
