//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECDataUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class XELAuditSpecificationDetail
    {
        public long IDetailID { get; set; }
        public long JobID { get; set; }
        public System.DateTime EVENT_TIME { get; set; }
        public string LOGIN_NAME { get; set; }
        public string SERVER_NAME { get; set; }
        public string DATABASE_NAME { get; set; }
        public string APPLICATION_NAME { get; set; }
        public string STATEMENT { get; set; }
        public byte[] KEYVALUE { get; set; }
        public int SROCode { get; set; }
        public string HOST_NAME { get; set; }
        public long TransmissionID { get; set; }
    
        public virtual XELReadJobDetails XELReadJobDetails { get; set; }
        public virtual XELTransmissionLog XELTransmissionLog { get; set; }
    }
}
