//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ECDataAPI.SRToCentralComService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SRToCentralComServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SRToCentralComService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback XELRootDirectoryInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback XELFileDownloadPathVerifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback XELFileDownloadOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifykeyforDatabaseRestorationOperationCompleted;
        
        private System.Threading.SendOrPostCallback DBRestorationAcknowledgementOperationCompleted;
        
        private System.Threading.SendOrPostCallback DBRestorationSaveOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback DBRestoreVerifyOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback DBRestoreSaveInsertScriptExecutionDeatailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveGeneratedScriptFileForDB_RESOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadScriptPathVerifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadScriptForRectificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CentralizeDiagnosticHealthCheckupDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveActionsForDHCOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSecureCodeTemperedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SRToCentralComService() {
            this.Url = global::ECDataAPI.Properties.Settings.Default.ECDataAPI_SRToCentralComService_SRToCentralComService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event XELRootDirectoryInfoCompletedEventHandler XELRootDirectoryInfoCompleted;
        
        /// <remarks/>
        public event XELFileDownloadPathVerifyCompletedEventHandler XELFileDownloadPathVerifyCompleted;
        
        /// <remarks/>
        public event XELFileDownloadCompletedEventHandler XELFileDownloadCompleted;
        
        /// <remarks/>
        public event VerifykeyforDatabaseRestorationCompletedEventHandler VerifykeyforDatabaseRestorationCompleted;
        
        /// <remarks/>
        public event DBRestorationAcknowledgementCompletedEventHandler DBRestorationAcknowledgementCompleted;
        
        /// <remarks/>
        public event DBRestorationSaveOTPCompletedEventHandler DBRestorationSaveOTPCompleted;
        
        /// <remarks/>
        public event DBRestoreVerifyOTPCompletedEventHandler DBRestoreVerifyOTPCompleted;
        
        /// <remarks/>
        public event DBRestoreSaveInsertScriptExecutionDeatailsCompletedEventHandler DBRestoreSaveInsertScriptExecutionDeatailsCompleted;
        
        /// <remarks/>
        public event SaveGeneratedScriptFileForDB_RESCompletedEventHandler SaveGeneratedScriptFileForDB_RESCompleted;
        
        /// <remarks/>
        public event DownloadScriptPathVerifyCompletedEventHandler DownloadScriptPathVerifyCompleted;
        
        /// <remarks/>
        public event DownloadScriptForRectificationCompletedEventHandler DownloadScriptForRectificationCompleted;
        
        /// <remarks/>
        public event CentralizeDiagnosticHealthCheckupDataCompletedEventHandler CentralizeDiagnosticHealthCheckupDataCompleted;
        
        /// <remarks/>
        public event GetActiveActionsForDHCCompletedEventHandler GetActiveActionsForDHCCompleted;
        
        /// <remarks/>
        public event UpdateSecureCodeTemperedCompletedEventHandler UpdateSecureCodeTemperedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XELRootDirectoryInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public XELFilesResModel XELRootDirectoryInfo(XELFilesReqModel reqModel) {
            object[] results = this.Invoke("XELRootDirectoryInfo", new object[] {
                        reqModel});
            return ((XELFilesResModel)(results[0]));
        }
        
        /// <remarks/>
        public void XELRootDirectoryInfoAsync(XELFilesReqModel reqModel) {
            this.XELRootDirectoryInfoAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void XELRootDirectoryInfoAsync(XELFilesReqModel reqModel, object userState) {
            if ((this.XELRootDirectoryInfoOperationCompleted == null)) {
                this.XELRootDirectoryInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXELRootDirectoryInfoOperationCompleted);
            }
            this.InvokeAsync("XELRootDirectoryInfo", new object[] {
                        reqModel}, this.XELRootDirectoryInfoOperationCompleted, userState);
        }
        
        private void OnXELRootDirectoryInfoOperationCompleted(object arg) {
            if ((this.XELRootDirectoryInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XELRootDirectoryInfoCompleted(this, new XELRootDirectoryInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XELFileDownloadPathVerify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public XELFilesResModel XELFileDownloadPathVerify(XELFilesReqModel reqModel) {
            object[] results = this.Invoke("XELFileDownloadPathVerify", new object[] {
                        reqModel});
            return ((XELFilesResModel)(results[0]));
        }
        
        /// <remarks/>
        public void XELFileDownloadPathVerifyAsync(XELFilesReqModel reqModel) {
            this.XELFileDownloadPathVerifyAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void XELFileDownloadPathVerifyAsync(XELFilesReqModel reqModel, object userState) {
            if ((this.XELFileDownloadPathVerifyOperationCompleted == null)) {
                this.XELFileDownloadPathVerifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXELFileDownloadPathVerifyOperationCompleted);
            }
            this.InvokeAsync("XELFileDownloadPathVerify", new object[] {
                        reqModel}, this.XELFileDownloadPathVerifyOperationCompleted, userState);
        }
        
        private void OnXELFileDownloadPathVerifyOperationCompleted(object arg) {
            if ((this.XELFileDownloadPathVerifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XELFileDownloadPathVerifyCompleted(this, new XELFileDownloadPathVerifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XELFileDownload", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public XELFilesResModel XELFileDownload(XELFilesReqModel reqModel) {
            object[] results = this.Invoke("XELFileDownload", new object[] {
                        reqModel});
            return ((XELFilesResModel)(results[0]));
        }
        
        /// <remarks/>
        public void XELFileDownloadAsync(XELFilesReqModel reqModel) {
            this.XELFileDownloadAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void XELFileDownloadAsync(XELFilesReqModel reqModel, object userState) {
            if ((this.XELFileDownloadOperationCompleted == null)) {
                this.XELFileDownloadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXELFileDownloadOperationCompleted);
            }
            this.InvokeAsync("XELFileDownload", new object[] {
                        reqModel}, this.XELFileDownloadOperationCompleted, userState);
        }
        
        private void OnXELFileDownloadOperationCompleted(object arg) {
            if ((this.XELFileDownloadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XELFileDownloadCompleted(this, new XELFileDownloadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifykeyforDatabaseRestoration", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DBRestoreResModel VerifykeyforDatabaseRestoration(DBRestoreReqModel reqModel) {
            object[] results = this.Invoke("VerifykeyforDatabaseRestoration", new object[] {
                        reqModel});
            return ((DBRestoreResModel)(results[0]));
        }
        
        /// <remarks/>
        public void VerifykeyforDatabaseRestorationAsync(DBRestoreReqModel reqModel) {
            this.VerifykeyforDatabaseRestorationAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void VerifykeyforDatabaseRestorationAsync(DBRestoreReqModel reqModel, object userState) {
            if ((this.VerifykeyforDatabaseRestorationOperationCompleted == null)) {
                this.VerifykeyforDatabaseRestorationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifykeyforDatabaseRestorationOperationCompleted);
            }
            this.InvokeAsync("VerifykeyforDatabaseRestoration", new object[] {
                        reqModel}, this.VerifykeyforDatabaseRestorationOperationCompleted, userState);
        }
        
        private void OnVerifykeyforDatabaseRestorationOperationCompleted(object arg) {
            if ((this.VerifykeyforDatabaseRestorationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifykeyforDatabaseRestorationCompleted(this, new VerifykeyforDatabaseRestorationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DBRestorationAcknowledgement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DBRestoreResModel DBRestorationAcknowledgement(DBRestoreSaveDBReqModel reqModel) {
            object[] results = this.Invoke("DBRestorationAcknowledgement", new object[] {
                        reqModel});
            return ((DBRestoreResModel)(results[0]));
        }
        
        /// <remarks/>
        public void DBRestorationAcknowledgementAsync(DBRestoreSaveDBReqModel reqModel) {
            this.DBRestorationAcknowledgementAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void DBRestorationAcknowledgementAsync(DBRestoreSaveDBReqModel reqModel, object userState) {
            if ((this.DBRestorationAcknowledgementOperationCompleted == null)) {
                this.DBRestorationAcknowledgementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDBRestorationAcknowledgementOperationCompleted);
            }
            this.InvokeAsync("DBRestorationAcknowledgement", new object[] {
                        reqModel}, this.DBRestorationAcknowledgementOperationCompleted, userState);
        }
        
        private void OnDBRestorationAcknowledgementOperationCompleted(object arg) {
            if ((this.DBRestorationAcknowledgementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DBRestorationAcknowledgementCompleted(this, new DBRestorationAcknowledgementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DBRestorationSaveOTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DBRestoreResModel DBRestorationSaveOTP(DBRestoreReqModel reqModel) {
            object[] results = this.Invoke("DBRestorationSaveOTP", new object[] {
                        reqModel});
            return ((DBRestoreResModel)(results[0]));
        }
        
        /// <remarks/>
        public void DBRestorationSaveOTPAsync(DBRestoreReqModel reqModel) {
            this.DBRestorationSaveOTPAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void DBRestorationSaveOTPAsync(DBRestoreReqModel reqModel, object userState) {
            if ((this.DBRestorationSaveOTPOperationCompleted == null)) {
                this.DBRestorationSaveOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDBRestorationSaveOTPOperationCompleted);
            }
            this.InvokeAsync("DBRestorationSaveOTP", new object[] {
                        reqModel}, this.DBRestorationSaveOTPOperationCompleted, userState);
        }
        
        private void OnDBRestorationSaveOTPOperationCompleted(object arg) {
            if ((this.DBRestorationSaveOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DBRestorationSaveOTPCompleted(this, new DBRestorationSaveOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DBRestoreVerifyOTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DBRestoreResModel DBRestoreVerifyOTP(DBRestoreReqModel reqModel) {
            object[] results = this.Invoke("DBRestoreVerifyOTP", new object[] {
                        reqModel});
            return ((DBRestoreResModel)(results[0]));
        }
        
        /// <remarks/>
        public void DBRestoreVerifyOTPAsync(DBRestoreReqModel reqModel) {
            this.DBRestoreVerifyOTPAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void DBRestoreVerifyOTPAsync(DBRestoreReqModel reqModel, object userState) {
            if ((this.DBRestoreVerifyOTPOperationCompleted == null)) {
                this.DBRestoreVerifyOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDBRestoreVerifyOTPOperationCompleted);
            }
            this.InvokeAsync("DBRestoreVerifyOTP", new object[] {
                        reqModel}, this.DBRestoreVerifyOTPOperationCompleted, userState);
        }
        
        private void OnDBRestoreVerifyOTPOperationCompleted(object arg) {
            if ((this.DBRestoreVerifyOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DBRestoreVerifyOTPCompleted(this, new DBRestoreVerifyOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DBRestoreSaveInsertScriptExecutionDeatails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DBRestoreSaveInsertScriptExecutionDeatails(DBRestoreSaveDBReqModel reqModel) {
            this.Invoke("DBRestoreSaveInsertScriptExecutionDeatails", new object[] {
                        reqModel});
        }
        
        /// <remarks/>
        public void DBRestoreSaveInsertScriptExecutionDeatailsAsync(DBRestoreSaveDBReqModel reqModel) {
            this.DBRestoreSaveInsertScriptExecutionDeatailsAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void DBRestoreSaveInsertScriptExecutionDeatailsAsync(DBRestoreSaveDBReqModel reqModel, object userState) {
            if ((this.DBRestoreSaveInsertScriptExecutionDeatailsOperationCompleted == null)) {
                this.DBRestoreSaveInsertScriptExecutionDeatailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDBRestoreSaveInsertScriptExecutionDeatailsOperationCompleted);
            }
            this.InvokeAsync("DBRestoreSaveInsertScriptExecutionDeatails", new object[] {
                        reqModel}, this.DBRestoreSaveInsertScriptExecutionDeatailsOperationCompleted, userState);
        }
        
        private void OnDBRestoreSaveInsertScriptExecutionDeatailsOperationCompleted(object arg) {
            if ((this.DBRestoreSaveInsertScriptExecutionDeatailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DBRestoreSaveInsertScriptExecutionDeatailsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveGeneratedScriptFileForDB_RES", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ScriptSaveRESModel SaveGeneratedScriptFileForDB_RES(ScriptSaveREQModel reqModel) {
            object[] results = this.Invoke("SaveGeneratedScriptFileForDB_RES", new object[] {
                        reqModel});
            return ((ScriptSaveRESModel)(results[0]));
        }
        
        /// <remarks/>
        public void SaveGeneratedScriptFileForDB_RESAsync(ScriptSaveREQModel reqModel) {
            this.SaveGeneratedScriptFileForDB_RESAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void SaveGeneratedScriptFileForDB_RESAsync(ScriptSaveREQModel reqModel, object userState) {
            if ((this.SaveGeneratedScriptFileForDB_RESOperationCompleted == null)) {
                this.SaveGeneratedScriptFileForDB_RESOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveGeneratedScriptFileForDB_RESOperationCompleted);
            }
            this.InvokeAsync("SaveGeneratedScriptFileForDB_RES", new object[] {
                        reqModel}, this.SaveGeneratedScriptFileForDB_RESOperationCompleted, userState);
        }
        
        private void OnSaveGeneratedScriptFileForDB_RESOperationCompleted(object arg) {
            if ((this.SaveGeneratedScriptFileForDB_RESCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveGeneratedScriptFileForDB_RESCompleted(this, new SaveGeneratedScriptFileForDB_RESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadScriptPathVerify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ScriptSaveRESModel DownloadScriptPathVerify(ScriptSaveREQModel reqModel) {
            object[] results = this.Invoke("DownloadScriptPathVerify", new object[] {
                        reqModel});
            return ((ScriptSaveRESModel)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadScriptPathVerifyAsync(ScriptSaveREQModel reqModel) {
            this.DownloadScriptPathVerifyAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void DownloadScriptPathVerifyAsync(ScriptSaveREQModel reqModel, object userState) {
            if ((this.DownloadScriptPathVerifyOperationCompleted == null)) {
                this.DownloadScriptPathVerifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadScriptPathVerifyOperationCompleted);
            }
            this.InvokeAsync("DownloadScriptPathVerify", new object[] {
                        reqModel}, this.DownloadScriptPathVerifyOperationCompleted, userState);
        }
        
        private void OnDownloadScriptPathVerifyOperationCompleted(object arg) {
            if ((this.DownloadScriptPathVerifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadScriptPathVerifyCompleted(this, new DownloadScriptPathVerifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadScriptForRectification", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ScriptSaveRESModel DownloadScriptForRectification(ScriptSaveREQModel reqModel) {
            object[] results = this.Invoke("DownloadScriptForRectification", new object[] {
                        reqModel});
            return ((ScriptSaveRESModel)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadScriptForRectificationAsync(ScriptSaveREQModel reqModel) {
            this.DownloadScriptForRectificationAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void DownloadScriptForRectificationAsync(ScriptSaveREQModel reqModel, object userState) {
            if ((this.DownloadScriptForRectificationOperationCompleted == null)) {
                this.DownloadScriptForRectificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadScriptForRectificationOperationCompleted);
            }
            this.InvokeAsync("DownloadScriptForRectification", new object[] {
                        reqModel}, this.DownloadScriptForRectificationOperationCompleted, userState);
        }
        
        private void OnDownloadScriptForRectificationOperationCompleted(object arg) {
            if ((this.DownloadScriptForRectificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadScriptForRectificationCompleted(this, new DownloadScriptForRectificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CentralizeDiagnosticHealthCheckupData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DiagnosticHealthCheckupResModel CentralizeDiagnosticHealthCheckupData(DiagnosticHealthCheckupReqModel reqModel) {
            object[] results = this.Invoke("CentralizeDiagnosticHealthCheckupData", new object[] {
                        reqModel});
            return ((DiagnosticHealthCheckupResModel)(results[0]));
        }
        
        /// <remarks/>
        public void CentralizeDiagnosticHealthCheckupDataAsync(DiagnosticHealthCheckupReqModel reqModel) {
            this.CentralizeDiagnosticHealthCheckupDataAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void CentralizeDiagnosticHealthCheckupDataAsync(DiagnosticHealthCheckupReqModel reqModel, object userState) {
            if ((this.CentralizeDiagnosticHealthCheckupDataOperationCompleted == null)) {
                this.CentralizeDiagnosticHealthCheckupDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCentralizeDiagnosticHealthCheckupDataOperationCompleted);
            }
            this.InvokeAsync("CentralizeDiagnosticHealthCheckupData", new object[] {
                        reqModel}, this.CentralizeDiagnosticHealthCheckupDataOperationCompleted, userState);
        }
        
        private void OnCentralizeDiagnosticHealthCheckupDataOperationCompleted(object arg) {
            if ((this.CentralizeDiagnosticHealthCheckupDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CentralizeDiagnosticHealthCheckupDataCompleted(this, new CentralizeDiagnosticHealthCheckupDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActiveActionsForDHC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ActiveActionsForDHC GetActiveActionsForDHC() {
            object[] results = this.Invoke("GetActiveActionsForDHC", new object[0]);
            return ((ActiveActionsForDHC)(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveActionsForDHCAsync() {
            this.GetActiveActionsForDHCAsync(null);
        }
        
        /// <remarks/>
        public void GetActiveActionsForDHCAsync(object userState) {
            if ((this.GetActiveActionsForDHCOperationCompleted == null)) {
                this.GetActiveActionsForDHCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveActionsForDHCOperationCompleted);
            }
            this.InvokeAsync("GetActiveActionsForDHC", new object[0], this.GetActiveActionsForDHCOperationCompleted, userState);
        }
        
        private void OnGetActiveActionsForDHCOperationCompleted(object arg) {
            if ((this.GetActiveActionsForDHCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveActionsForDHCCompleted(this, new GetActiveActionsForDHCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateSecureCodeTempered", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateSecureCodeTempered(DiagnosticMaster reqModel) {
            this.Invoke("UpdateSecureCodeTempered", new object[] {
                        reqModel});
        }
        
        /// <remarks/>
        public void UpdateSecureCodeTemperedAsync(DiagnosticMaster reqModel) {
            this.UpdateSecureCodeTemperedAsync(reqModel, null);
        }
        
        /// <remarks/>
        public void UpdateSecureCodeTemperedAsync(DiagnosticMaster reqModel, object userState) {
            if ((this.UpdateSecureCodeTemperedOperationCompleted == null)) {
                this.UpdateSecureCodeTemperedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSecureCodeTemperedOperationCompleted);
            }
            this.InvokeAsync("UpdateSecureCodeTempered", new object[] {
                        reqModel}, this.UpdateSecureCodeTemperedOperationCompleted, userState);
        }
        
        private void OnUpdateSecureCodeTemperedOperationCompleted(object arg) {
            if ((this.UpdateSecureCodeTemperedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSecureCodeTemperedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class XELFilesReqModel {
        
        private string[] rootDirectoryPathListField;
        
        private string fileDownloadPathField;
        
        /// <remarks/>
        public string[] RootDirectoryPathList {
            get {
                return this.rootDirectoryPathListField;
            }
            set {
                this.rootDirectoryPathListField = value;
            }
        }
        
        /// <remarks/>
        public string FileDownloadPath {
            get {
                return this.fileDownloadPathField;
            }
            set {
                this.fileDownloadPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DiagnosticActionMaster {
        
        private int actionIdField;
        
        /// <remarks/>
        public int ActionId {
            get {
                return this.actionIdField;
            }
            set {
                this.actionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ActiveActionsForDHC {
        
        private DiagnosticActionMaster[] diagnosticActionMastersField;
        
        private bool isErrorField;
        
        private string errorMsgField;
        
        /// <remarks/>
        public DiagnosticActionMaster[] diagnosticActionMasters {
            get {
                return this.diagnosticActionMastersField;
            }
            set {
                this.diagnosticActionMastersField = value;
            }
        }
        
        /// <remarks/>
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DiagnosticHealthCheckupResModel {
        
        private bool isErrorField;
        
        private string errorMsgField;
        
        /// <remarks/>
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DiagnosticDetails {
        
        private int detailIdField;
        
        private int diagnosticIdField;
        
        private int actionIdField;
        
        private bool actionStatusField;
        
        private string errorDescriptionField;
        
        private string diagnosticOutputField;
        
        private int masterIdField;
        
        /// <remarks/>
        public int DetailId {
            get {
                return this.detailIdField;
            }
            set {
                this.detailIdField = value;
            }
        }
        
        /// <remarks/>
        public int DiagnosticId {
            get {
                return this.diagnosticIdField;
            }
            set {
                this.diagnosticIdField = value;
            }
        }
        
        /// <remarks/>
        public int ActionId {
            get {
                return this.actionIdField;
            }
            set {
                this.actionIdField = value;
            }
        }
        
        /// <remarks/>
        public bool ActionStatus {
            get {
                return this.actionStatusField;
            }
            set {
                this.actionStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string DiagnosticOutput {
            get {
                return this.diagnosticOutputField;
            }
            set {
                this.diagnosticOutputField = value;
            }
        }
        
        /// <remarks/>
        public int MasterId {
            get {
                return this.masterIdField;
            }
            set {
                this.masterIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DiagnosticMaster {
        
        private int diagnosticIdField;
        
        private System.DateTime diagnosticDateField;
        
        private System.DateTime startTimeField;
        
        private System.Nullable<System.DateTime> completionTimeField;
        
        private string requestIPField;
        
        private string loginIdField;
        
        private int isSuccessfulField;
        
        private bool isCentralizedField;
        
        private string secureCodeField;
        
        private int officeCodeField;
        
        private int masterIDField;
        
        /// <remarks/>
        public int DiagnosticId {
            get {
                return this.diagnosticIdField;
            }
            set {
                this.diagnosticIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DiagnosticDate {
            get {
                return this.diagnosticDateField;
            }
            set {
                this.diagnosticDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CompletionTime {
            get {
                return this.completionTimeField;
            }
            set {
                this.completionTimeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestIP {
            get {
                return this.requestIPField;
            }
            set {
                this.requestIPField = value;
            }
        }
        
        /// <remarks/>
        public string LoginId {
            get {
                return this.loginIdField;
            }
            set {
                this.loginIdField = value;
            }
        }
        
        /// <remarks/>
        public int IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCentralized {
            get {
                return this.isCentralizedField;
            }
            set {
                this.isCentralizedField = value;
            }
        }
        
        /// <remarks/>
        public string SecureCode {
            get {
                return this.secureCodeField;
            }
            set {
                this.secureCodeField = value;
            }
        }
        
        /// <remarks/>
        public int OfficeCode {
            get {
                return this.officeCodeField;
            }
            set {
                this.officeCodeField = value;
            }
        }
        
        /// <remarks/>
        public int MasterID {
            get {
                return this.masterIDField;
            }
            set {
                this.masterIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DiagnosticHealthCheckupReqModel {
        
        private DiagnosticMaster[] diagnosticMastersField;
        
        private DiagnosticDetails[] diagnosticDetailsField;
        
        private int sROCodeField;
        
        /// <remarks/>
        public DiagnosticMaster[] DiagnosticMasters {
            get {
                return this.diagnosticMastersField;
            }
            set {
                this.diagnosticMastersField = value;
            }
        }
        
        /// <remarks/>
        public DiagnosticDetails[] DiagnosticDetails {
            get {
                return this.diagnosticDetailsField;
            }
            set {
                this.diagnosticDetailsField = value;
            }
        }
        
        /// <remarks/>
        public int SROCode {
            get {
                return this.sROCodeField;
            }
            set {
                this.sROCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ScriptSaveRESModel {
        
        private bool isScriptSavedSuccessfullyField;
        
        private string errorMsgField;
        
        private string savedScriptFilePathField;
        
        private bool isFileExistAtDownloadPathField;
        
        private byte[] fileContentFieldField;
        
        private bool isFileFetchedSuccesfullyField;
        
        /// <remarks/>
        public bool IsScriptSavedSuccessfully {
            get {
                return this.isScriptSavedSuccessfullyField;
            }
            set {
                this.isScriptSavedSuccessfullyField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        public string SavedScriptFilePath {
            get {
                return this.savedScriptFilePathField;
            }
            set {
                this.savedScriptFilePathField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFileExistAtDownloadPath {
            get {
                return this.isFileExistAtDownloadPathField;
            }
            set {
                this.isFileExistAtDownloadPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileContentField {
            get {
                return this.fileContentFieldField;
            }
            set {
                this.fileContentFieldField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFileFetchedSuccesfully {
            get {
                return this.isFileFetchedSuccesfullyField;
            }
            set {
                this.isFileFetchedSuccesfullyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ScriptSaveREQModel {
        
        private byte[] scriptContentField;
        
        private int sROCodeField;
        
        private bool isDroField;
        
        private string fileDownloadPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ScriptContent {
            get {
                return this.scriptContentField;
            }
            set {
                this.scriptContentField = value;
            }
        }
        
        /// <remarks/>
        public int SROCode {
            get {
                return this.sROCodeField;
            }
            set {
                this.sROCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDro {
            get {
                return this.isDroField;
            }
            set {
                this.isDroField = value;
            }
        }
        
        /// <remarks/>
        public string FileDownloadPath {
            get {
                return this.fileDownloadPathField;
            }
            set {
                this.fileDownloadPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OfficeColumnDetails {
        
        private string tableNameField;
        
        private string columnNameField;
        
        private string columnDefaultField;
        
        private string dataTypeField;
        
        private System.Nullable<int> charMaxLengthField;
        
        private System.Nullable<int> numericPrecisionField;
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
            }
        }
        
        /// <remarks/>
        public string ColumnDefault {
            get {
                return this.columnDefaultField;
            }
            set {
                this.columnDefaultField = value;
            }
        }
        
        /// <remarks/>
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> charMaxLength {
            get {
                return this.charMaxLengthField;
            }
            set {
                this.charMaxLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumericPrecision {
            get {
                return this.numericPrecisionField;
            }
            set {
                this.numericPrecisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OfficeTableDetails {
        
        private string databaseNameField;
        
        private string tableSchemaField;
        
        private string tableNameField;
        
        /// <remarks/>
        public string DatabaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
            }
        }
        
        /// <remarks/>
        public string TableSchema {
            get {
                return this.tableSchemaField;
            }
            set {
                this.tableSchemaField = value;
            }
        }
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TableWiseCounts {
        
        private string tableNameField;
        
        private int rowsCountField;
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        public int RowsCount {
            get {
                return this.rowsCountField;
            }
            set {
                this.rowsCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DBRestoreSaveDBReqModel {
        
        private int initIdField;
        
        private int sROCodeField;
        
        private int lastDocumentIDField;
        
        private string lastFinalRegistrationNumberField;
        
        private string lastDocumentDateOfRegistrationField;
        
        private int lastMarrigeIDField;
        
        private string lastMarriageRegistrationNumberField;
        
        private string lastMarriageRegistrationDateField;
        
        private int lastNoticeIDField;
        
        private string lastNoticeNumberField;
        
        private string lastNoticeIssuedDateField;
        
        private int lastFirmIdField;
        
        private string lastFirmNumberField;
        
        private string lastFirmRegistrationDateField;
        
        private int dbRestoreActionField;
        
        private System.DateTime dbRestoreDateTimeField;
        
        private bool dbRestoreIsSuccessfulField;
        
        private string dbRestoreErrorDescriptionField;
        
        private int dbConsistencyCheckActionField;
        
        private System.DateTime dbConsistencyCheckDateTimeField;
        
        private bool dbConsistencyCheckIsSuccessfulField;
        
        private string dbConsistencyCheckErrorDescriptionField;
        
        private int dbVerifyOfficeCodeActionField;
        
        private System.DateTime dbVerifyOfficeCodeDateTimeField;
        
        private bool dbVerifyOfficeCodeIsSuccessfulField;
        
        private string dbVerifyOfficeCodeErrorDescriptionField;
        
        private int dbCreateKaveriUserActionField;
        
        private System.DateTime dbCreateKaveriUserDateTimeField;
        
        private bool dbCreateKaveriUserIsSuccessfulField;
        
        private string dbCreateKaveriUserErrorDescriptionField;
        
        private int dbEnableAuditLogActionField;
        
        private System.DateTime dbEnableAuditLogDateTimeField;
        
        private bool dbEnableAuditLogIsSuccessfulField;
        
        private string dbEnableAuditLogErrorDescriptionField;
        
        private System.Nullable<int> scriptIdField;
        
        private int sendLastIDField;
        
        private System.DateTime sendLastIdDateTimeField;
        
        private bool sendLastIdIsSuccessfulField;
        
        private string sendLastIdErrorDescriptionField;
        
        private System.DateTime dB_Restored_upto_BAK_DTField;
        
        private int executeScriptActionField;
        
        private System.DateTime executeScriptDateTimeField;
        
        private bool executeScriptIsSuccessfulField;
        
        private string executeScriptErrorDescriptionField;
        
        private bool isErrorField;
        
        private string errorMsgField;
        
        private int dBInsertScriptIdField;
        
        private TableWiseCounts[] tableWiseCounts2Field;
        
        private string dB_Restored_upto_BAK_SizeField;
        
        private string documentRegistrationCDNumberField;
        
        private string marriageRegistrationCDNumberField;
        
        private string dB_Restored_upto_BAK_FileNameField;
        
        private OfficeTableDetails[] officeTableDetailsListField;
        
        private OfficeColumnDetails[] officeColumnDetailsListField;
        
        private int sendDBSchemaIDField;
        
        private System.DateTime sendDBSchemaDateTimeField;
        
        private bool sendDBSchemaIsSuccessfulField;
        
        private string sendDBSchmeaErrorMessageField;
        
        private string presentDateTimeField;
        
        private string documentNumberField;
        
        /// <remarks/>
        public int InitId {
            get {
                return this.initIdField;
            }
            set {
                this.initIdField = value;
            }
        }
        
        /// <remarks/>
        public int SROCode {
            get {
                return this.sROCodeField;
            }
            set {
                this.sROCodeField = value;
            }
        }
        
        /// <remarks/>
        public int LastDocumentID {
            get {
                return this.lastDocumentIDField;
            }
            set {
                this.lastDocumentIDField = value;
            }
        }
        
        /// <remarks/>
        public string LastFinalRegistrationNumber {
            get {
                return this.lastFinalRegistrationNumberField;
            }
            set {
                this.lastFinalRegistrationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LastDocumentDateOfRegistration {
            get {
                return this.lastDocumentDateOfRegistrationField;
            }
            set {
                this.lastDocumentDateOfRegistrationField = value;
            }
        }
        
        /// <remarks/>
        public int LastMarrigeID {
            get {
                return this.lastMarrigeIDField;
            }
            set {
                this.lastMarrigeIDField = value;
            }
        }
        
        /// <remarks/>
        public string LastMarriageRegistrationNumber {
            get {
                return this.lastMarriageRegistrationNumberField;
            }
            set {
                this.lastMarriageRegistrationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LastMarriageRegistrationDate {
            get {
                return this.lastMarriageRegistrationDateField;
            }
            set {
                this.lastMarriageRegistrationDateField = value;
            }
        }
        
        /// <remarks/>
        public int LastNoticeID {
            get {
                return this.lastNoticeIDField;
            }
            set {
                this.lastNoticeIDField = value;
            }
        }
        
        /// <remarks/>
        public string LastNoticeNumber {
            get {
                return this.lastNoticeNumberField;
            }
            set {
                this.lastNoticeNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LastNoticeIssuedDate {
            get {
                return this.lastNoticeIssuedDateField;
            }
            set {
                this.lastNoticeIssuedDateField = value;
            }
        }
        
        /// <remarks/>
        public int LastFirmId {
            get {
                return this.lastFirmIdField;
            }
            set {
                this.lastFirmIdField = value;
            }
        }
        
        /// <remarks/>
        public string LastFirmNumber {
            get {
                return this.lastFirmNumberField;
            }
            set {
                this.lastFirmNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LastFirmRegistrationDate {
            get {
                return this.lastFirmRegistrationDateField;
            }
            set {
                this.lastFirmRegistrationDateField = value;
            }
        }
        
        /// <remarks/>
        public int DbRestoreAction {
            get {
                return this.dbRestoreActionField;
            }
            set {
                this.dbRestoreActionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DbRestoreDateTime {
            get {
                return this.dbRestoreDateTimeField;
            }
            set {
                this.dbRestoreDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool DbRestoreIsSuccessful {
            get {
                return this.dbRestoreIsSuccessfulField;
            }
            set {
                this.dbRestoreIsSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string DbRestoreErrorDescription {
            get {
                return this.dbRestoreErrorDescriptionField;
            }
            set {
                this.dbRestoreErrorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int DbConsistencyCheckAction {
            get {
                return this.dbConsistencyCheckActionField;
            }
            set {
                this.dbConsistencyCheckActionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DbConsistencyCheckDateTime {
            get {
                return this.dbConsistencyCheckDateTimeField;
            }
            set {
                this.dbConsistencyCheckDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool DbConsistencyCheckIsSuccessful {
            get {
                return this.dbConsistencyCheckIsSuccessfulField;
            }
            set {
                this.dbConsistencyCheckIsSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string DbConsistencyCheckErrorDescription {
            get {
                return this.dbConsistencyCheckErrorDescriptionField;
            }
            set {
                this.dbConsistencyCheckErrorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int DbVerifyOfficeCodeAction {
            get {
                return this.dbVerifyOfficeCodeActionField;
            }
            set {
                this.dbVerifyOfficeCodeActionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DbVerifyOfficeCodeDateTime {
            get {
                return this.dbVerifyOfficeCodeDateTimeField;
            }
            set {
                this.dbVerifyOfficeCodeDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool DbVerifyOfficeCodeIsSuccessful {
            get {
                return this.dbVerifyOfficeCodeIsSuccessfulField;
            }
            set {
                this.dbVerifyOfficeCodeIsSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string DbVerifyOfficeCodeErrorDescription {
            get {
                return this.dbVerifyOfficeCodeErrorDescriptionField;
            }
            set {
                this.dbVerifyOfficeCodeErrorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int DbCreateKaveriUserAction {
            get {
                return this.dbCreateKaveriUserActionField;
            }
            set {
                this.dbCreateKaveriUserActionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DbCreateKaveriUserDateTime {
            get {
                return this.dbCreateKaveriUserDateTimeField;
            }
            set {
                this.dbCreateKaveriUserDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool DbCreateKaveriUserIsSuccessful {
            get {
                return this.dbCreateKaveriUserIsSuccessfulField;
            }
            set {
                this.dbCreateKaveriUserIsSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string DbCreateKaveriUserErrorDescription {
            get {
                return this.dbCreateKaveriUserErrorDescriptionField;
            }
            set {
                this.dbCreateKaveriUserErrorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int DbEnableAuditLogAction {
            get {
                return this.dbEnableAuditLogActionField;
            }
            set {
                this.dbEnableAuditLogActionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DbEnableAuditLogDateTime {
            get {
                return this.dbEnableAuditLogDateTimeField;
            }
            set {
                this.dbEnableAuditLogDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool DbEnableAuditLogIsSuccessful {
            get {
                return this.dbEnableAuditLogIsSuccessfulField;
            }
            set {
                this.dbEnableAuditLogIsSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string DbEnableAuditLogErrorDescription {
            get {
                return this.dbEnableAuditLogErrorDescriptionField;
            }
            set {
                this.dbEnableAuditLogErrorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ScriptId {
            get {
                return this.scriptIdField;
            }
            set {
                this.scriptIdField = value;
            }
        }
        
        /// <remarks/>
        public int SendLastID {
            get {
                return this.sendLastIDField;
            }
            set {
                this.sendLastIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendLastIdDateTime {
            get {
                return this.sendLastIdDateTimeField;
            }
            set {
                this.sendLastIdDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool SendLastIdIsSuccessful {
            get {
                return this.sendLastIdIsSuccessfulField;
            }
            set {
                this.sendLastIdIsSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string SendLastIdErrorDescription {
            get {
                return this.sendLastIdErrorDescriptionField;
            }
            set {
                this.sendLastIdErrorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DB_Restored_upto_BAK_DT {
            get {
                return this.dB_Restored_upto_BAK_DTField;
            }
            set {
                this.dB_Restored_upto_BAK_DTField = value;
            }
        }
        
        /// <remarks/>
        public int ExecuteScriptAction {
            get {
                return this.executeScriptActionField;
            }
            set {
                this.executeScriptActionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExecuteScriptDateTime {
            get {
                return this.executeScriptDateTimeField;
            }
            set {
                this.executeScriptDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool ExecuteScriptIsSuccessful {
            get {
                return this.executeScriptIsSuccessfulField;
            }
            set {
                this.executeScriptIsSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string ExecuteScriptErrorDescription {
            get {
                return this.executeScriptErrorDescriptionField;
            }
            set {
                this.executeScriptErrorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        public int DBInsertScriptId {
            get {
                return this.dBInsertScriptIdField;
            }
            set {
                this.dBInsertScriptIdField = value;
            }
        }
        
        /// <remarks/>
        public TableWiseCounts[] TableWiseCounts2 {
            get {
                return this.tableWiseCounts2Field;
            }
            set {
                this.tableWiseCounts2Field = value;
            }
        }
        
        /// <remarks/>
        public string DB_Restored_upto_BAK_Size {
            get {
                return this.dB_Restored_upto_BAK_SizeField;
            }
            set {
                this.dB_Restored_upto_BAK_SizeField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentRegistrationCDNumber {
            get {
                return this.documentRegistrationCDNumberField;
            }
            set {
                this.documentRegistrationCDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MarriageRegistrationCDNumber {
            get {
                return this.marriageRegistrationCDNumberField;
            }
            set {
                this.marriageRegistrationCDNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DB_Restored_upto_BAK_FileName {
            get {
                return this.dB_Restored_upto_BAK_FileNameField;
            }
            set {
                this.dB_Restored_upto_BAK_FileNameField = value;
            }
        }
        
        /// <remarks/>
        public OfficeTableDetails[] OfficeTableDetailsList {
            get {
                return this.officeTableDetailsListField;
            }
            set {
                this.officeTableDetailsListField = value;
            }
        }
        
        /// <remarks/>
        public OfficeColumnDetails[] OfficeColumnDetailsList {
            get {
                return this.officeColumnDetailsListField;
            }
            set {
                this.officeColumnDetailsListField = value;
            }
        }
        
        /// <remarks/>
        public int SendDBSchemaID {
            get {
                return this.sendDBSchemaIDField;
            }
            set {
                this.sendDBSchemaIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendDBSchemaDateTime {
            get {
                return this.sendDBSchemaDateTimeField;
            }
            set {
                this.sendDBSchemaDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool SendDBSchemaIsSuccessful {
            get {
                return this.sendDBSchemaIsSuccessfulField;
            }
            set {
                this.sendDBSchemaIsSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string SendDBSchmeaErrorMessage {
            get {
                return this.sendDBSchmeaErrorMessageField;
            }
            set {
                this.sendDBSchmeaErrorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string PresentDateTime {
            get {
                return this.presentDateTimeField;
            }
            set {
                this.presentDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DBRestoreResModel {
        
        private bool isErrorField;
        
        private string errorMsgField;
        
        private bool isKeyorOTPIsCorrectField;
        
        private int sROCodeField;
        
        private int initIDField;
        
        private string sROMobileNumberField;
        
        private byte[] dB_Insert_ScriptField;
        
        private int dBInsertScriptIdField;
        
        private string dB_Res_Script_QueryField;
        
        private int statusIdField;
        
        /// <remarks/>
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        public bool IsKeyorOTPIsCorrect {
            get {
                return this.isKeyorOTPIsCorrectField;
            }
            set {
                this.isKeyorOTPIsCorrectField = value;
            }
        }
        
        /// <remarks/>
        public int SROCode {
            get {
                return this.sROCodeField;
            }
            set {
                this.sROCodeField = value;
            }
        }
        
        /// <remarks/>
        public int InitID {
            get {
                return this.initIDField;
            }
            set {
                this.initIDField = value;
            }
        }
        
        /// <remarks/>
        public string SROMobileNumber {
            get {
                return this.sROMobileNumberField;
            }
            set {
                this.sROMobileNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DB_Insert_Script {
            get {
                return this.dB_Insert_ScriptField;
            }
            set {
                this.dB_Insert_ScriptField = value;
            }
        }
        
        /// <remarks/>
        public int DBInsertScriptId {
            get {
                return this.dBInsertScriptIdField;
            }
            set {
                this.dBInsertScriptIdField = value;
            }
        }
        
        /// <remarks/>
        public string DB_Res_Script_Query {
            get {
                return this.dB_Res_Script_QueryField;
            }
            set {
                this.dB_Res_Script_QueryField = value;
            }
        }
        
        /// <remarks/>
        public int StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DBRestoreReqModel {
        
        private string keyorOTPField;
        
        private int initIDField;
        
        private int sROCodeField;
        
        /// <remarks/>
        public string KeyorOTP {
            get {
                return this.keyorOTPField;
            }
            set {
                this.keyorOTPField = value;
            }
        }
        
        /// <remarks/>
        public int InitID {
            get {
                return this.initIDField;
            }
            set {
                this.initIDField = value;
            }
        }
        
        /// <remarks/>
        public int SROCode {
            get {
                return this.sROCodeField;
            }
            set {
                this.sROCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RootDirInfoModel {
        
        private string rootDirectoryField;
        
        private string totalSpaceField;
        
        private string usedSpaceField;
        
        private string freeSpaceField;
        
        private string xELSpaceField;
        
        /// <remarks/>
        public string RootDirectory {
            get {
                return this.rootDirectoryField;
            }
            set {
                this.rootDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string TotalSpace {
            get {
                return this.totalSpaceField;
            }
            set {
                this.totalSpaceField = value;
            }
        }
        
        /// <remarks/>
        public string UsedSpace {
            get {
                return this.usedSpaceField;
            }
            set {
                this.usedSpaceField = value;
            }
        }
        
        /// <remarks/>
        public string FreeSpace {
            get {
                return this.freeSpaceField;
            }
            set {
                this.freeSpaceField = value;
            }
        }
        
        /// <remarks/>
        public string XELSpace {
            get {
                return this.xELSpaceField;
            }
            set {
                this.xELSpaceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class XELFilesResModel {
        
        private RootDirInfoModel[] rootDirInfoModelListField;
        
        private bool isFileExistAtDownloadPathField;
        
        private byte[] fileContentFieldField;
        
        private string errorMsgField;
        
        /// <remarks/>
        public RootDirInfoModel[] RootDirInfoModelList {
            get {
                return this.rootDirInfoModelListField;
            }
            set {
                this.rootDirInfoModelListField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFileExistAtDownloadPath {
            get {
                return this.isFileExistAtDownloadPathField;
            }
            set {
                this.isFileExistAtDownloadPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileContentField {
            get {
                return this.fileContentFieldField;
            }
            set {
                this.fileContentFieldField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void XELRootDirectoryInfoCompletedEventHandler(object sender, XELRootDirectoryInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XELRootDirectoryInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XELRootDirectoryInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public XELFilesResModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((XELFilesResModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void XELFileDownloadPathVerifyCompletedEventHandler(object sender, XELFileDownloadPathVerifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XELFileDownloadPathVerifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XELFileDownloadPathVerifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public XELFilesResModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((XELFilesResModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void XELFileDownloadCompletedEventHandler(object sender, XELFileDownloadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XELFileDownloadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XELFileDownloadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public XELFilesResModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((XELFilesResModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void VerifykeyforDatabaseRestorationCompletedEventHandler(object sender, VerifykeyforDatabaseRestorationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifykeyforDatabaseRestorationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifykeyforDatabaseRestorationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DBRestoreResModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DBRestoreResModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DBRestorationAcknowledgementCompletedEventHandler(object sender, DBRestorationAcknowledgementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DBRestorationAcknowledgementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DBRestorationAcknowledgementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DBRestoreResModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DBRestoreResModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DBRestorationSaveOTPCompletedEventHandler(object sender, DBRestorationSaveOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DBRestorationSaveOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DBRestorationSaveOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DBRestoreResModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DBRestoreResModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DBRestoreVerifyOTPCompletedEventHandler(object sender, DBRestoreVerifyOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DBRestoreVerifyOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DBRestoreVerifyOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DBRestoreResModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DBRestoreResModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DBRestoreSaveInsertScriptExecutionDeatailsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveGeneratedScriptFileForDB_RESCompletedEventHandler(object sender, SaveGeneratedScriptFileForDB_RESCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveGeneratedScriptFileForDB_RESCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveGeneratedScriptFileForDB_RESCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ScriptSaveRESModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ScriptSaveRESModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DownloadScriptPathVerifyCompletedEventHandler(object sender, DownloadScriptPathVerifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadScriptPathVerifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadScriptPathVerifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ScriptSaveRESModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ScriptSaveRESModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DownloadScriptForRectificationCompletedEventHandler(object sender, DownloadScriptForRectificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadScriptForRectificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadScriptForRectificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ScriptSaveRESModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ScriptSaveRESModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CentralizeDiagnosticHealthCheckupDataCompletedEventHandler(object sender, CentralizeDiagnosticHealthCheckupDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CentralizeDiagnosticHealthCheckupDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CentralizeDiagnosticHealthCheckupDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DiagnosticHealthCheckupResModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DiagnosticHealthCheckupResModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetActiveActionsForDHCCompletedEventHandler(object sender, GetActiveActionsForDHCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveActionsForDHCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveActionsForDHCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActiveActionsForDHC Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActiveActionsForDHC)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateSecureCodeTemperedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591